import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BRIDGE_KEY = Deno.env.get("VH_BRIDGE_KEY") || "";
const ALLOWED = new Set(["https://vohoanginvest.com","https://www.vohoanginvest.com","https://hoangonthi.github.io"]);

function cors(req: Request){const o=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://www.vohoanginvest.com","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"content-type,x-bridge-key","Cache-Control":"no-store","Vary":"Origin"};}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}});}
function sh(extra:Record<string,string>={}){return{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,...extra};}
function n(v:unknown):number|null{const x=Number(v);return Number.isFinite(x)?x:null;}
function first(obj:any,keys:string[]){for(const k of keys){const v=k.split(".").reduce((a,b)=>a?.[b],obj);if(v!==undefined&&v!==null&&v!=="")return v;}return null;}
function round(v:number,d=2){const p=10**d;return Math.round(v*p)/p;}
function clamp(v:number,a=0,b=100){return Math.max(a,Math.min(b,v));}
function vnDate(v:string|Date){const d=v instanceof Date?v:new Date(v);const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const g=(t:string)=>p.find(x=>x.type===t)?.value||"";return`${g("year")}-${g("month")}-${g("day")}`;}
function vnMinute(v:string|Date){const d=v instanceof Date?v:new Date(v);const p=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Ho_Chi_Minh",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(d);const g=(t:string)=>Number(p.find(x=>x.type===t)?.value||0);return g("hour")*60+g("minute");}
function marketIndex(ctx:any,sym:string){return Array.isArray(ctx?.indexes)?ctx.indexes.find((x:any)=>String(x?.symbol||"").toUpperCase()===sym.toUpperCase())||null:null;}
function compactStock(x:any){return{symbol:String(x?.symbol||x?.code||"").toUpperCase(),price:n(first(x,["price","close","last"])),change:n(x?.change),change_pct:n(first(x,["change_pct","changePct","pct"])),volume:n(x?.volume)};}
function normalizeSectors(input:any,fallback:any[]){const raw=Array.isArray(input?.sector_watchlists)?input.sector_watchlists:[];const src=raw.length?raw:fallback;return src.map((x:any)=>({key:String(x?.key||x?.symbol||x?.name||""),name:String(x?.name||x?.symbol||"Nhóm ngành"),change_pct:n(x?.change_pct),adv:n(x?.adv),flat:n(x?.flat),dec:n(x?.dec),member_count:n(x?.member_count),valid_count:n(x?.valid_count),coverage:n(x?.coverage),breadth_balance:n(x?.breadth_balance),top_gainers:Array.isArray(x?.top_gainers)?x.top_gainers.map(compactStock).filter((s:any)=>s.symbol):[],top_losers:Array.isArray(x?.top_losers)?x.top_losers.map(compactStock).filter((s:any)=>s.symbol):[],source:raw.length?"AmiBroker Watch Lists":String(x?.source||"market-feed")})).filter((x:any)=>x.change_pct!==null);}

function normalize(input:any){
  const t=input?.technical||{},ctx=input?.market_context||{},idx=marketIndex(ctx,"VN-INDEX")||{},mi=ctx?.market_intelligence||{};
  const reference=n(first(t,["reference","ref","prev_close"]))??n(first(idx,["reference","ref","prev_close"]));
  const value=n(first(t,["value","last","close"]))??n(first(idx,["value","close","last"]));
  const change=n(first(t,["change","change_point"]))??n(first(idx,["change","change_point"]));
  let pct=n(first(t,["change_pct","pct"]))??n(first(idx,["change_pct","pct"]));if(pct===null&&value!==null&&reference!==null&&reference!==0)pct=(value/reference-1)*100;
  const high=n(first(t,["high","session_high"]))??n(idx?.high),low=n(first(t,["low","session_low"]))??n(idx?.low);
  const rebound=n(t?.rebound_from_low)??(value!==null&&low!==null?value-low:null),drop=n(t?.drop_from_high)??(value!==null&&high!==null?high-value:null);
  const adv=n(idx?.adv)??n(first(mi,["breadth.adv"])),flat=n(idx?.flat)??n(first(mi,["breadth.flat"])),dec=n(idx?.dec)??n(first(mi,["breadth.dec"]));
  const total=[adv,flat,dec].every(x=>x!==null)?adv!+flat!+dec!:null;const balance=total&&total>0?(adv!-dec!)/total:n(first(mi,["breadth.balance"]));
  const sectors=normalizeSectors(input,Array.isArray(mi?.sectors)?mi.sectors:[]);
  const vn30=(Array.isArray(ctx?.vn30_stocks)?ctx.vn30_stocks:Array.isArray(ctx?.vn30?.stocks)?ctx.vn30.stocks:[]).map(compactStock).filter((x:any)=>x.symbol);
  return{technical:t,technical_available:Boolean(input?.technical_available??Object.keys(t).length),local_first:Boolean(input?.local_first),engine_version:"3.0",local_memory:input?.local_memory||{},market:{vnindex:{value,reference,change,change_pct:pct,high,low,rebound_from_low:rebound,drop_from_high:drop,adv,flat,dec,breadth_balance:balance,value_b:n(first(idx,["value_b","total_value_b"]))??n(first(mi,["flow.value_b"]))},state:mi?.state||null,breadth:mi?.breadth||null,flow:mi?.flow||null,sectors,alerts:Array.isArray(mi?.alerts)?mi.alerts:[]},watchlist_sectors:sectors,vn30_stocks:vn30,context_received_at:first(ctx,["relay_received_at","received_at","updated_at"])};
}
function metrics(p:any){const v=p?.market?.vnindex||{},t=p?.technical||{};return{value:n(v.value),reference:n(v.reference),change:n(v.change),pct:n(v.change_pct),high:n(v.high),low:n(v.low),rebound:n(v.rebound_from_low),drop:n(v.drop_from_high),adv:n(v.adv),flat:n(v.flat),dec:n(v.dec),breadth:n(v.breadth_balance),valueB:n(v.value_b),ma10:n(t.ma10),ma20:n(t.ma20),ma50:n(t.ma50),vwap:n(t.vwap),rsi14:n(t.rsi14),macd:n(t.macd),signal:n(t.macd_signal),support:n(t.support_near),resistance:n(t.resistance_near),prevHigh:n(t.prev_high),prevLow:n(t.prev_low),high20:n(t.high20),low20:n(t.low20)};}
function memoryMetrics(x:any){if(!x)return null;return{value:n(x.value),change:n(x.change),pct:n(x.pct),breadth:n(x.breadth_balance)};}
function sectorRows(p:any){return Array.isArray(p?.market?.sectors)?p.market.sectors:[];}
function validSectors(p:any){return [...sectorRows(p)].filter((x:any)=>n(x?.change_pct)!==null&&(n(x?.coverage)===null||Number(x.coverage)>=.35));}
function sectorKey(x:any){return String(x?.key||x?.symbol||x?.name||"");}
function sectorByKey(rows:any[],key:string){return rows.find((x:any)=>sectorKey(x)===key)||null;}
function findPast(rows:any[],capturedAt:string,min:number){const target=new Date(capturedAt).getTime()-min*60000;let best:any=null,diff=Infinity;for(const r of rows){const d=Math.abs(new Date(r.captured_at).getTime()-target);if(d<diff&&d<=180000){best=r;diff=d;}}return best;}
function pastMetrics(payload:any,rows:any[],capturedAt:string,min:number){const local=memoryMetrics(payload?.local_memory?.[`m${min}`]);if(local)return local;const row=findPast(rows,capturedAt,min);return row?metrics(row.payload):null;}
function pastSectors(payload:any,rows:any[],capturedAt:string,min:number){const local=payload?.local_memory?.[`m${min}`];if(Array.isArray(local?.sectors))return local.sectors;const row=findPast(rows,capturedAt,min);return row?sectorRows(row.payload):[];}
function pctDistance(a:number|null,b:number|null){return a!==null&&b!==null&&a!==0?Math.abs(a-b)/Math.abs(a)*100:null;}
function fmt(x:number|null,d=2){return x===null?"—":new Intl.NumberFormat("vi-VN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(x);}
function signed(x:number|null,d=2){return x===null?"—":`${x>0?"+":""}${fmt(x,d)}`;}

function buildZones(p:any){const m=metrics(p),v=m.value;const levels=[
  {key:"ma10",label:"MA10",value:m.ma10},{key:"ma20",label:"MA20",value:m.ma20},{key:"ma50",label:"MA50",value:m.ma50},{key:"vwap",label:"VWAP",value:m.vwap},
  {key:"support",label:"hỗ trợ gần",value:m.support},{key:"resistance",label:"cản gần",value:m.resistance},{key:"prevHigh",label:"đỉnh phiên trước",value:m.prevHigh},{key:"prevLow",label:"đáy phiên trước",value:m.prevLow},{key:"high20",label:"đỉnh 20 phiên",value:m.high20},{key:"low20",label:"đáy 20 phiên",value:m.low20}
].filter(x=>x.value!==null&&x.value!>0);
  const below=levels.filter(x=>v!==null&&x.value!<v).map(x=>({...x,distance_pct:pctDistance(v,x.value)})).sort((a,b)=>Number(a.distance_pct)-Number(b.distance_pct));
  const above=levels.filter(x=>v!==null&&x.value!>v).map(x=>({...x,distance_pct:pctDistance(v,x.value)})).sort((a,b)=>Number(a.distance_pct)-Number(b.distance_pct));
  const near=[...levels].map(x=>({...x,distance_pct:pctDistance(v,x.value)})).filter(x=>x.distance_pct!==null&&x.distance_pct<=.35).sort((a,b)=>Number(a.distance_pct)-Number(b.distance_pct));
  return{nearest_below:below[0]||null,nearest_above:above[0]||null,near,position:v!==null?{above_ma10:m.ma10===null?null:v>=m.ma10,above_ma20:m.ma20===null?null:v>=m.ma20,above_vwap:m.vwap===null?null:v>=m.vwap}:null};
}
function roleForSector(s:any){const p=n(s?.change_pct)??0,b=n(s?.breadth_balance);if(p>=.8&&(b===null||b>=.15))return"dẫn dắt";if(p>=.25)return"hỗ trợ";if(p<=-.8&&(b===null||b<=-.15))return"gây áp lực mạnh";if(p<=-.25)return"gây áp lực";return"trung tính";}
function buildDriver(p:any,p15Sectors:any[]){const m=metrics(p),rows=validSectors(p).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct));if(!rows.length)return null;const direction=(m.change??0)>=0?"up":"down";const s=direction==="up"?rows.find((x:any)=>Number(x.change_pct)>0)||rows[0]:[...rows].reverse().find((x:any)=>Number(x.change_pct)<0)||rows.at(-1);if(!s)return null;const before=sectorByKey(p15Sectors,sectorKey(s)),delta15=n(s.change_pct)!-(n(before?.change_pct)??n(s.change_pct)!);const bb=n(s.breadth_balance);let score=Math.min(40,Math.abs(n(s.change_pct)??0)*22)+Math.min(20,Math.abs(delta15)*35);if(direction==="up"&&bb!==null&&bb>.2)score+=20;if(direction==="down"&&bb!==null&&bb<-.2)score+=20;const players=direction==="up"?(s.top_gainers||[]):(s.top_losers||[]);score+=Math.min(15,players.length*5);return{direction,sector:{...s,role:roleForSector(s)},delta_15m:round(delta15,3),confidence_score:Math.round(clamp(score)),confidence:score>=65?"CAO":score>=42?"VỪA":"THẤP",players:players.slice(0,3)};}
function buildWorld(p:any,rows:any[],capturedAt:string){
  const m=metrics(p),m5=pastMetrics(p,rows,capturedAt,5),m15=pastMetrics(p,rows,capturedAt,15),m30=pastMetrics(p,rows,capturedAt,30),s15=pastSectors(p,rows,capturedAt,15);
  const d5=m.value!==null&&m5?.value!==null?m.value-m5.value:null,d15=m.value!==null&&m15?.value!==null?m.value-m15.value:null,d30=m.value!==null&&m30?.value!==null?m.value-m30.value:null;
  const b15=m.breadth!==null&&m15?.breadth!==null?m.breadth-m15.breadth:null;const sectors=validSectors(p).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct));
  const strongest=sectors.slice(0,3).map((x:any)=>({...x,role:roleForSector(x)})),weakest=sectors.slice(-3).reverse().map((x:any)=>({...x,role:roleForSector(x)}));const driver=buildDriver(p,s15),zones=buildZones(p);
  let match="Thế trận đang cân bằng.";if(d15!==null&&d15>=3&&(b15===null||b15>=.05))match="Thế trận đang cải thiện, lực hồi có độ lan tỏa tốt hơn.";else if(d15!==null&&d15<=-3&&(b15===null||b15<=-.05))match="Áp lực đang tăng lên, cả chỉ số lẫn mặt bằng cổ phiếu cùng yếu đi.";else if((m.change??0)>0&&m.breadth!==null&&m.breadth<-.12)match="Chỉ số đang tốt hơn mặt bằng cổ phiếu; sức mạnh còn tập trung.";else if((m.change??0)<0&&m.breadth!==null&&m.breadth>.12)match="Chỉ số còn đỏ nhưng mặt bằng cổ phiếu đỡ xấu hơn điểm số thể hiện.";
  return{ball:{value:m.value,change:m.change,pct:m.pct,high:m.high,low:m.low,rebound_from_low:m.rebound,drop_from_high:m.drop,delta_5m:d5===null?null:round(d5,2),delta_15m:d15===null?null:round(d15,2),delta_30m:d30===null?null:round(d30,2)},match:{label:match,breadth:{adv:m.adv,flat:m.flat,dec:m.dec,balance:m.breadth,delta_15m:b15===null?null:round(b15,3)},flow:p?.market?.flow||null},lines:{strongest,weakest},driver,zones,technical:{ma10:m.ma10,ma20:m.ma20,ma50:m.ma50,vwap:m.vwap,rsi14:m.rsi14,macd:m.macd,signal:m.signal},generated_at:capturedAt};
}

type Candidate={type:string;key:string;severity:number;tone:string;title:string;facts:any};
function sign(x:number|null){if(x===null||Math.abs(x)<.01)return 0;return x>0?1:-1;}
function crossedUp(c:number|null,p1:number|null,p2:number|null,l0:number|null,l1:number|null,l2:number|null){return c!==null&&p1!==null&&p2!==null&&l0!==null&&l1!==null&&l2!==null&&c>=l0&&p1>=l1&&p2<l2;}
function crossedDown(c:number|null,p1:number|null,p2:number|null,l0:number|null,l1:number|null,l2:number|null){return c!==null&&p1!==null&&p2!==null&&l0!==null&&l1!==null&&l2!==null&&c<=l0&&p1<=l1&&p2>l2;}
function detect(p:any,rows:any[],capturedAt:string,world:any):Candidate[]{
  const m=metrics(p),p1=rows[0]?metrics(rows[0].payload):null,p2=rows[1]?metrics(rows[1].payload):null,c:Candidate[]=[];
  if(!p1){c.push({type:"SESSION_BASELINE",key:"baseline",severity:1,tone:"neutral",title:"Bắt đầu theo dõi câu chuyện của phiên",facts:{world}});return c;}
  if(p2){const s0=sign(m.change??(m.value!==null&&m.reference!==null?m.value-m.reference:null)),s1=sign(p1.change??(p1.value!==null&&p1.reference!==null?p1.value-p1.reference:null)),s2=sign(p2.change??(p2.value!==null&&p2.reference!==null?p2.value-p2.reference:null));if(s0>0&&s1>0&&s2<0)c.push({type:"RED_TO_GREEN",key:"red-to-green",severity:4,tone:"positive",title:"VN-Index quay lại sắc xanh",facts:{world}});if(s0<0&&s1<0&&s2>0)c.push({type:"GREEN_TO_RED",key:"green-to-red",severity:4,tone:"danger",title:"VN-Index chuyển lại sắc đỏ",facts:{world}});for(const [k,label] of [["ma10","MA10"],["ma20","MA20"],["vwap","VWAP"]] as const){if(crossedUp(m.value,p1.value,p2.value,m[k],p1[k],p2[k]))c.push({type:`CROSS_${k.toUpperCase()}_UP`,key:`${k}-up`,severity:k==="ma20"?4:3,tone:"positive",title:`VN-Index lấy lại ${label}`,facts:{world,level:m[k],level_name:label}});if(crossedDown(m.value,p1.value,p2.value,m[k],p1[k],p2[k]))c.push({type:`CROSS_${k.toUpperCase()}_DOWN`,key:`${k}-down`,severity:k==="ma20"?4:3,tone:"warning",title:`VN-Index mất ${label}`,facts:{world,level:m[k],level_name:label}});}}
  for(const th of [10,7,4]){if(m.rebound!==null&&p1.rebound!==null&&m.rebound>=th&&p1.rebound<th){c.push({type:"REBOUND_FROM_LOW",key:`rebound-${th}`,severity:th>=7?4:3,tone:"positive",title:`VN-Index hồi ${th} điểm từ đáy phiên`,facts:{world,threshold:th}});break;}}
  for(const th of [10,7,4]){if(m.drop!==null&&p1.drop!==null&&m.drop>=th&&p1.drop<th){c.push({type:"DROP_FROM_HIGH",key:`drop-${th}`,severity:th>=7?4:3,tone:"warning",title:`VN-Index lùi ${th} điểm từ đỉnh phiên`,facts:{world,threshold:th}});break;}}
  const d15=n(world?.ball?.delta_15m),bd15=n(world?.match?.breadth?.delta_15m);if(d15!==null&&bd15!==null&&d15>=4&&bd15>=.10)c.push({type:"STORY_TURN_POSITIVE",key:"story-positive",severity:4,tone:"positive",title:"Thế trận đang chuyển tích cực hơn",facts:{world}});if(d15!==null&&bd15!==null&&d15<=-4&&bd15<=-.10)c.push({type:"STORY_TURN_NEGATIVE",key:"story-negative",severity:4,tone:"warning",title:"Thế trận đang xấu đi rõ",facts:{world}});
  if(world?.driver&&Math.abs(n(world.driver.delta_15m)??0)>=.35&&world.driver.confidence_score>=50)c.push({type:"DRIVER_ACCELERATE",key:`driver-${sectorKey(world.driver.sector)}`,severity:3,tone:world.driver.direction==="up"?"positive":"warning",title:`${world.driver.sector.name} đang ${world.driver.direction==="up"?"mạnh lên":"yếu đi"} rõ`,facts:{world}});
  const s15=pastSectors(p,rows,capturedAt,15),topNow=world?.lines?.strongest?.[0],topOld=[...s15].filter((x:any)=>n(x?.change_pct)!==null).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct))[0];if(topNow&&topOld&&sectorKey(topNow)!==sectorKey(topOld)&&Number(topNow.change_pct)>=.4)c.push({type:"LEADERSHIP_ROTATION",key:`rotate-${sectorKey(topNow)}`,severity:2,tone:"neutral",title:`${topNow.name} vươn lên nhóm nổi bật`,facts:{world,previous_sector:topOld}});
  if(m.pct!==null&&m.breadth!==null&&m.pct>=0&&m.breadth<=-.12)c.push({type:"INDEX_GREEN_BREADTH_WEAK",key:"green-breadth-weak",severity:4,tone:"warning",title:"Chỉ số xanh nhưng mặt bằng cổ phiếu chưa theo kịp",facts:{world}});
  const above=world?.zones?.nearest_above,below=world?.zones?.nearest_below,old5=pastMetrics(p,rows,capturedAt,5);if(above&&n(above.distance_pct)!==null&&Number(above.distance_pct)<=.25&&old5?.value!==null&&pctDistance(old5.value,n(above.value))!>.4)c.push({type:"APPROACH_RESISTANCE",key:`zone-up-${above.key}`,severity:3,tone:"neutral",title:`VN-Index tiến sát ${above.label}`,facts:{world,zone:above}});if(below&&n(below.distance_pct)!==null&&Number(below.distance_pct)<=.25&&old5?.value!==null&&pctDistance(old5.value,n(below.value))!>.4)c.push({type:"APPROACH_SUPPORT",key:`zone-down-${below.key}`,severity:3,tone:"warning",title:`VN-Index lùi sát ${below.label}`,facts:{world,zone:below}});
  const pace=n(first(p,["market.flow.pace_ratio_15m"]));if(pace!==null&&pace>=1.35)c.push({type:"LIQUIDITY_ACCELERATE",key:"liquidity-accelerate",severity:2,tone:"neutral",title:"Dòng tiền 15 phút đang tăng tốc",facts:{world,pace_ratio:round(pace,2)}});
  return c.sort((a,b)=>b.severity-a.severity);
}

function breadthSentence(w:any){const b=w?.match?.breadth;if(n(b?.adv)===null||n(b?.dec)===null)return"";if(Number(b.adv)>Number(b.dec)*1.25)return`Độ rộng nghiêng tích cực với ${Math.round(b.adv)} mã tăng so với ${Math.round(b.dec)} mã giảm.`;if(Number(b.dec)>Number(b.adv)*1.25)return`Độ rộng còn yếu với ${Math.round(b.dec)} mã giảm so với ${Math.round(b.adv)} mã tăng.`;return`Độ rộng khá cân bằng: ${Math.round(b.adv)} mã tăng và ${Math.round(b.dec)} mã giảm.`;}
function driverSentence(w:any){const d=w?.driver;if(!d?.sector)return"Chưa có một nhóm đủ nổi bật để giải thích nhịp vận động hiện tại.";const s=d.sector,players=(d.players||[]).map((x:any)=>x.symbol).filter(Boolean).slice(0,3);let t=d.direction==="up"?`Nhịp vận động đang đi cùng sự cải thiện của ${s.name}, bình quân ${signed(n(s.change_pct),2)}%`:`Áp lực đang đi cùng sự suy yếu của ${s.name}, bình quân ${signed(n(s.change_pct),2)}%`;if(n(s.adv)!==null&&n(s.dec)!==null)t+=` với ${Math.round(s.adv)} mã tăng/${Math.round(s.dec)} mã giảm`;t+=".";if(players.length)t+=` Các mã nổi bật trong nhóm: ${players.join(", ")}.`;if(d.confidence==="THẤP")t+=` Mối liên hệ này mới ở mức tham khảo, chưa đủ để xem là lực chi phối chính.`;return t;}
function zoneSentence(w:any){const z=w?.zones;if(!z)return"";const a=z.nearest_above,b=z.nearest_below;if(a&&Number(a.distance_pct)<=.6&&b&&Number(b.distance_pct)<=.6)return`VN-Index đang nằm giữa ${b.label} ${fmt(n(b.value),1)} phía dưới và ${a.label} ${fmt(n(a.value),1)} phía trên.`;if(a&&Number(a.distance_pct)<=.6)return`Phía trước gần nhất là ${a.label} quanh ${fmt(n(a.value),1)} điểm.`;if(b&&Number(b.distance_pct)<=.6)return`Vùng đỡ gần nhất nằm quanh ${b.label} ${fmt(n(b.value),1)} điểm.`;return"";}
function scenario(w:any){const a=w?.zones?.nearest_above,b=w?.zones?.nearest_below,d=w?.driver,bd=n(w?.match?.breadth?.delta_15m);if(a&&Number(a.distance_pct)<=.6)return`Nếu VN-Index vượt ${fmt(n(a.value),1)} đồng thời độ rộng tiếp tục cải thiện và nhóm dẫn giữ nhịp, kịch bản tích cực được củng cố. Nếu chỉ số không vượt được vùng này và độ rộng thu hẹp, cần đề phòng nhịp hồi hụt hơi.`;if(b&&Number(b.distance_pct)<=.6)return`Nếu VN-Index giữ được ${fmt(n(b.value),1)} và độ rộng không xấu thêm, thị trường còn cơ hội ổn định lại. Nếu mất vùng này cùng lúc nhóm yếu mở rộng, rủi ro sẽ tăng.`;if(d?.direction==="up"||bd!==null&&bd>0)return"Theo dõi xem sức mạnh có lan sang thêm các nhóm và số mã tăng có tiếp tục mở rộng hay không; nếu không, đà cải thiện hiện tại có thể chỉ mang tính cục bộ.";return"Theo dõi độ rộng, tốc độ dòng tiền và nhóm đang gây áp lực; chỉ khi các biến này cùng cải thiện thì câu chuyện ngắn hạn mới tích cực hơn.";}

async function safeFunction(slug:string,timeout=1800){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(`${SUPABASE_URL}/functions/v1/${slug}`,{signal:ctl.signal,headers:{Accept:"application/json"}});if(!r.ok)return null;return await r.json();}catch{return null;}finally{clearTimeout(tm);}}
async function outsideContext(){const [der,news,macro]=await Promise.all([safeFunction("derivatives-feed"),safeFunction("news-intelligence-preview-v2",2200),safeFunction("macro-anchor-public",2200)]);const droot=Array.isArray(der)?der[0]:der?.data||der?.snapshot||der||{};const trend=String(first(droot,["trend","current.trend","snapshot.trend"])||"").toUpperCase();const ne=Array.isArray(news?.events)?news.events:[];const now=Date.now();const topNews=ne.find((x:any)=>{const age=now-new Date(x?.published_at||x?.last_seen_at||0).getTime();return age>=0&&age<=6*3600000&&Number(x?.impact_score||0)>=65&&Number(x?.confidence_score||0)>=60;})||null;return{derivatives:trend?{trend,symbol:first(droot,["symbol","current.symbol","snapshot.symbol"]),last_price:n(first(droot,["last_price","current.last_price","snapshot.last_price"]))}:null,news:topNews?{title:String(topNews.title||""),direction:topNews.direction||null,impact_score:n(topNews.impact_score),confidence_score:n(topNews.confidence_score),source_name:topNews.source_name||null,published_at:topNews.published_at||topNews.last_seen_at||null}:null,macro:macro?.ok?{regime:macro.regime||null,horizon:macro.horizon||null,thesis:macro.thesis||null}:null};}
function outsideSentence(o:any){const bits:string[]=[];if(o?.derivatives?.trend==="TANG")bits.push("Phái sinh hiện nghiêng tăng, đây là tín hiệu tham khảo thêm cho thế trận cơ sở.");if(o?.derivatives?.trend==="GIAM")bits.push("Phái sinh hiện nghiêng giảm, đây là tín hiệu tham khảo thêm cho thế trận cơ sở.");if(o?.news?.title)bits.push(`Ngoài diễn biến giá, tin đáng chú ý đang được theo dõi: ${o.news.title}. Chưa dùng tin này để quy kết nguyên nhân trực tiếp nếu thị trường chưa xác nhận.`);return bits.slice(0,2).join(" ");}
function makeComment(c:Candidate,w:any,o:any){const ball=w.ball;let lead=`VN-Index hiện ở ${fmt(n(ball.value),2)} điểm, ${signed(n(ball.change),2)} điểm (${signed(n(ball.pct),2)}%).`;if(c.type==="REBOUND_FROM_LOW")lead=`VN-Index đã hồi khoảng ${fmt(n(ball.rebound_from_low),1)} điểm từ đáy phiên và hiện ở ${fmt(n(ball.value),2)} điểm.`;else if(c.type==="DROP_FROM_HIGH")lead=`VN-Index đã lùi khoảng ${fmt(n(ball.drop_from_high),1)} điểm từ đỉnh phiên và hiện ở ${fmt(n(ball.value),2)} điểm.`;else if(c.type==="RED_TO_GREEN")lead=`VN-Index đã quay lại sắc xanh sau nhịp yếu trước đó, hiện ở ${fmt(n(ball.value),2)} điểm.`;else if(c.type==="GREEN_TO_RED")lead=`VN-Index đã chuyển lại sắc đỏ, hiện ở ${fmt(n(ball.value),2)} điểm.`;else if(c.type.startsWith("CROSS_"))lead=`${c.title} quanh ${fmt(n(c.facts?.level),1)} điểm; chỉ số hiện ở ${fmt(n(ball.value),2)} điểm.`;else if(c.type==="STORY_TURN_POSITIVE"||c.type==="STORY_TURN_NEGATIVE")lead=`${w.match.label} VN-Index thay đổi ${signed(n(ball.delta_15m),2)} điểm trong khoảng 15 phút.`;else if(c.type==="DRIVER_ACCELERATE"||c.type==="LEADERSHIP_ROTATION")lead=`${c.title}. VN-Index hiện ở ${fmt(n(ball.value),2)} điểm.`;else if(c.type==="MATCH_RECAP")lead=`Rà soát nhanh thế trận: VN-Index ${signed(n(ball.change),2)} điểm, ${w.match.label.toLowerCase()}`;
  const body=[lead,breadthSentence(w),driverSentence(w),zoneSentence(w),outsideSentence(o)].filter(Boolean).join(" ");return{tone:c.tone,headline:c.title,body,watch_next:scenario(w),evidence:{world_model:w,outside_context:o,source:"AmiBroker technical + AmiBroker Watch Lists + market-feed",causality_rule:"Không quy kết nguyên nhân nếu không có bằng chứng đóng góp/đồng thời đủ mạnh."}};}

async function restGet(path:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:sh()});if(!r.ok)return[];try{return await r.json();}catch{return[];}}
async function upsertCurrent(row:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/market_live_current?on_conflict=id`,{method:"POST",headers:sh({"Content-Type":"application/json","Prefer":"resolution=merge-duplicates,return=minimal"}),body:JSON.stringify(row)});return r.ok;}
async function insert(table:string,row:any){const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:sh({"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify(row)});if(!r.ok)return null;try{return(await r.json())?.[0]||null;}catch{return null;}}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);if(!BRIDGE_KEY||req.headers.get("x-bridge-key")!==BRIDGE_KEY)return json(req,{ok:false,error:"UNAUTHORIZED"},401);
  let input:any;try{input=await req.json();}catch{return json(req,{ok:false,error:"INVALID_JSON"},400);}if(!input?.ok)return json(req,{ok:false,error:"INVALID_PAYLOAD"},400);
  const capturedAt=typeof input?.captured_at==="string"&&!Number.isNaN(new Date(input.captured_at).getTime())?new Date(input.captured_at).toISOString():new Date().toISOString();const marketDate=vnDate(capturedAt),payload=normalize(input),source=String(input?.source||"amibroker-live-v3"),sourceUpdatedAt=typeof input?.source_updated_at==="string"&&!Number.isNaN(new Date(input.source_updated_at).getTime())?new Date(input.source_updated_at).toISOString():null;
  const previous=await restGet(`market_live_snapshots?market_date=eq.${encodeURIComponent(marketDate)}&select=id,captured_at,payload&order=captured_at.desc&limit=45`);const world=buildWorld(payload,previous,capturedAt);payload.world_model=world;
  let candidates=detect(payload,previous,capturedAt,world);const recentEvents=await restGet(`market_live_events?market_date=eq.${encodeURIComponent(marketDate)}&select=event_key,detected_at,severity&order=detected_at.desc&limit=40`);let chosen:Candidate|null=null;
  for(const c of candidates){const last=recentEvents.find((x:any)=>x.event_key===c.key);if(!last){chosen=c;break;}const age=new Date(capturedAt).getTime()-new Date(last.detected_at).getTime();const cooldown=c.type.startsWith("APPROACH_")?12*60000:c.severity>=4?4*60000:7*60000;if(age>=cooldown){chosen=c;break;}}
  const lastComments=await restGet(`market_live_comments?market_date=eq.${encodeURIComponent(marketDate)}&select=id,published_at&order=published_at.desc&limit=1`);const lastCommentAge=lastComments.length?new Date(capturedAt).getTime()-new Date(lastComments[0].published_at).getTime():Infinity;if(!chosen&&lastCommentAge>=18*60000){const bucket=Math.floor(vnMinute(capturedAt)/20);chosen={type:"MATCH_RECAP",key:`recap-${bucket}`,severity:2,tone:"neutral",title:"Rà soát nhanh thế trận trong phiên",facts:{world}};}
  const currentStored=await upsertCurrent({id:"vietnam",market_date:marketDate,captured_at:capturedAt,source_updated_at:sourceUpdatedAt,source,payload,updated_at:new Date().toISOString()});const lastHistory=previous.length?new Date(previous[0].captured_at).getTime():0,dueHistory=!lastHistory||new Date(capturedAt).getTime()-lastHistory>=55000,mustStore=dueHistory||Boolean(chosen);let snapshot:any=null;if(mustStore)snapshot=await insert("market_live_snapshots",{market_date:marketDate,captured_at:capturedAt,source_updated_at:sourceUpdatedAt,source,payload});
  let event:any=null,comment:any=null;if(chosen&&snapshot){event=await insert("market_live_events",{market_date:marketDate,detected_at:capturedAt,snapshot_id:snapshot.id,event_type:chosen.type,event_key:chosen.key,severity:chosen.severity,tone:chosen.tone,title:chosen.title,facts:chosen.facts});if(event){const outside=await outsideContext(),built=makeComment(chosen,world,outside);comment=await insert("market_live_comments",{market_date:marketDate,published_at:capturedAt,event_id:event.id,snapshot_id:snapshot.id,tone:built.tone,headline:built.headline,body:built.body,watch_next:built.watch_next,evidence:built.evidence,source_mode:"narrative-world-v3"});}}
  return json(req,{ok:true,engine:"market-live-narrative-v3",current_stored:currentStored,history_stored:Boolean(snapshot),history_mode:"about-1-minute-plus-events",watchlist_sector_count:payload.watchlist_sectors.length,world_model:{match:world.match.label,driver:world.driver?.sector?.name||null,driver_confidence:world.driver?.confidence||null,nearest_above:world.zones?.nearest_above||null,nearest_below:world.zones?.nearest_below||null},published_comment:comment,event:event?{id:event.id,type:event.event_type,title:event.title}:null});
});
