import { supabaseClient } from './assets/js/supabase-client.js';
const $=s=>document.querySelector(s); const fmt=v=>v?new Intl.NumberFormat('vi-VN',{maximumFractionDigits:0}).format(v):'—';
const loginBox=$('#loginBox'),app=$('#app'),loginMsg=$('#loginMsg');
const nextPage=new URLSearchParams(location.search).get('next');
function fill(p={}){$('#displayName').value=p.display_name||'';$('#totalCapital').value=p.total_capital||'';$('#investableCapital').value=p.investable_capital||'';$('#cashBuffer').value=p.cash_buffer||'';$('#marginLimit').value=p.margin_limit_pct??0;$('#riskBudget').value=p.portfolio_risk_budget_pct??8;$('#maxPosition').value=p.max_position_pct??20;$('#maxDrawdown').value=p.max_drawdown_pct??20;$('#mCapital').textContent=fmt(p.investable_capital||p.total_capital);$('#mRisk').textContent=`${p.portfolio_risk_budget_pct??8}%`;$('#mPosition').textContent=`${p.max_position_pct??20}%`;$('#mDrawdown').textContent=`${p.max_drawdown_pct??20}%`;}
function friendly(error){const m=String(error?.message||'');if(m.includes('AUTH_REQUIRED'))return 'Phiên đăng nhập chưa sẵn sàng. Vui lòng đăng nhập lại.';if(m.includes('auth_user_id'))return 'Passport đang được đồng bộ. Hãy tải lại trang một lần.';return m||'Chưa tải được Investor Passport.'}
async function load(){loginMsg.textContent='Đang tải Investor Passport...';const {data,error}=await supabaseClient.rpc('investor_get_or_create_passport_v1');if(error){loginMsg.textContent=friendly(error);return}fill(data||{});loginBox.classList.add('hidden');app.classList.remove('hidden');loginMsg.textContent='';if(nextPage&&/^[a-z0-9-]+\.html$/i.test(nextPage)&&(data?.investable_capital||data?.total_capital)){history.replaceState({},'',location.pathname);location.href=nextPage;}}
$('#googleLogin').onclick=async()=>{loginMsg.textContent='Đang chuyển tới Google...';const redirectTo=location.origin+location.pathname+(nextPage?`?next=${encodeURIComponent(nextPage)}`:'');const {error}=await supabaseClient.auth.signInWithOAuth({provider:'google',options:{redirectTo,queryParams:{prompt:'select_account'}}});if(error)loginMsg.textContent=friendly(error)};
$('#savePassport').onclick=async()=>{const button=$('#savePassport');button.disabled=true;$('#saveMsg').textContent='Đang lưu...';const payload={display_name:$('#displayName').value.trim(),total_capital:$('#totalCapital').value,investable_capital:$('#investableCapital').value,cash_buffer:$('#cashBuffer').value,margin_limit_pct:$('#marginLimit').value,portfolio_risk_budget_pct:$('#riskBudget').value,max_position_pct:$('#maxPosition').value,max_drawdown_pct:$('#maxDrawdown').value,max_sector_pct:35};const {data,error}=await supabaseClient.rpc('investor_save_passport_v1',{p_payload:payload});$('#saveMsg').textContent=error?`Chưa lưu được: ${friendly(error)}`:'Đã lưu Investor Passport. 5 Decision Room sẽ dùng chung dữ liệu này.';if(data){fill(data);if(nextPage&&/^[a-z0-9-]+\.html$/i.test(nextPage)){setTimeout(()=>location.href=nextPage,450)}}button.disabled=false};
$('#logout').onclick=async()=>{await supabaseClient.auth.signOut();location.href='investor-os.html'};
const {data}=await supabaseClient.auth.getSession();if(data.session)await load();