import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ALLOWED_ORIGINS=new Set(["https://vohoanginvest.com","https://www.vohoanginvest.com","https://hoangonthi.github.io"]);
function cors(req:Request){const origin=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":ALLOWED_ORIGINS.has(origin)?origin:"https://www.vohoanginvest.com","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"content-type","Cache-Control":"no-store","Vary":"Origin"};}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}});}
function headers(){return{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`};}
function vnDate(value:string|Date){const d=value instanceof Date?value:new Date(value);const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const get=(t:string)=>p.find(x=>x.type===t)?.value||"";return`${get("year")}-${get("month")}-${get("day")}`;}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:null;}
function first(obj:any,keys:string[]){for(const key of keys){const v=key.split(".").reduce((a,b)=>a?.[b],obj);if(v!==undefined&&v!==null&&v!=="")return v;}return null;}
function compactSnapshot(row:any){if(!row)return null;const p=row.payload||{},v=p?.market?.vnindex||{},t=p?.technical||{},sectors=Array.isArray(p?.market?.sectors)?p.market.sectors:[],sorted=[...sectors].filter((x:any)=>n(x?.change_pct)!==null).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct)),stocks=Array.isArray(p?.vn30_stocks)?p.vn30_stocks:[],stockRows=[...stocks].filter((x:any)=>n(first(x,["change_pct","changePct","pct"]))!==null).sort((a:any,b:any)=>Number(first(b,["change_pct","changePct","pct"]))-Number(first(a,["change_pct","changePct","pct"])));return{id:row.id,captured_at:row.captured_at,technical_available:Boolean(p.technical_available),vnindex:{value:n(v.value),change:n(v.change),change_pct:n(v.change_pct),high:n(v.high),low:n(v.low),rebound_from_low:n(v.rebound_from_low),drop_from_high:n(v.drop_from_high),adv:n(v.adv),flat:n(v.flat),dec:n(v.dec),value_b:n(v.value_b)},technical:{ma10:n(first(t,["ma10","ma10_daily"])),ma20:n(first(t,["ma20","ma20_daily"])),ma50:n(first(t,["ma50","ma50_daily"])),vwap:n(first(t,["vwap"])),rsi14:n(first(t,["rsi14","rsi"])),macd:n(first(t,["macd"])),macd_signal:n(first(t,["macd_signal","signal"])),support_near:n(first(t,["support_near","support"])),resistance_near:n(first(t,["resistance_near","resistance"]))},state:p?.market?.state||null,breadth:p?.market?.breadth||null,flow:p?.market?.flow||null,sectors:{strongest:sorted.slice(0,3),weakest:sorted.slice(-3).reverse()},vn30:{gainers:stockRows.filter((x:any)=>Number(first(x,["change_pct","changePct","pct"]))>0).slice(0,3),losers:[...stockRows].reverse().filter((x:any)=>Number(first(x,["change_pct","changePct","pct"]))<0).slice(0,3)}};}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="GET")return json(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);const url=new URL(req.url),limit=Math.max(1,Math.min(40,Number(url.searchParams.get("limit")||20))),after=Math.max(0,Number(url.searchParams.get("after_id")||0)),today=vnDate(new Date());const snapshotResp=await fetch(`${SUPABASE_URL}/rest/v1/market_live_snapshots?market_date=eq.${today}&select=id,captured_at,payload&order=captured_at.desc&limit=1`,{headers:headers()});let snapshotRows:any[]=[];if(snapshotResp.ok){try{snapshotRows=await snapshotResp.json()}catch{}}let commentPath=`market_live_comments?market_date=eq.${today}`;if(after>0)commentPath+=`&id=gt.${after}&order=id.asc&limit=${limit}`;else commentPath+=`&order=published_at.desc,id.desc&limit=${limit}`;commentPath+=`&select=id,published_at,tone,headline,body,watch_next,evidence,source_mode,event_id,snapshot_id`;const commentsResp=await fetch(`${SUPABASE_URL}/rest/v1/${commentPath}`,{headers:headers()});let comments:any[]=[];if(commentsResp.ok){try{comments=await commentsResp.json()}catch{}}const latest=compactSnapshot(snapshotRows[0]||null);return json(req,{ok:true,market_date:today,latest,comments,latest_comment_id:comments.length?Math.max(...comments.map((x:any)=>Number(x.id)||0)):after,polling_seconds:10,note:"Bình luận được tạo khi hệ thống phát hiện thay đổi đáng kể; không phát liên tục theo từng snapshot."});});