import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.48.1";

const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const ALLOWED=new Set(["https://www.vohoanginvest.com","https://vohoanginvest.com","https://hoangonthi.github.io","http://localhost:5500","http://127.0.0.1:5500"]);
function cors(req:Request){const o=req.headers.get("origin")||"";return{"access-control-allow-origin":ALLOWED.has(o)?o:"https://www.vohoanginvest.com","vary":"Origin","access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"content-type","content-type":"application/json; charset=utf-8","cache-control":"public, max-age=60, s-maxage=180"}}
const res=(req:Request,b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors(req)});
const clean=(s:any)=>String(s||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const norm=(s:any)=>clean(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const clamp=(n:number)=>Math.min(100,Math.max(0,Math.round(n)));
function periodFrom(text:string,published:string|null){const t=norm(text),pub=published?new Date(published):null,py=pub&&!isNaN(pub.getTime())?pub.getUTCFullYear():new Date().getUTCFullYear();let year:number|null=null;const ym=t.match(/\b(20\d{2})\b/);if(ym)year=Number(ym[1]);let code:string|null=null,type:string|null=null;let m=t.match(/(?:quy|q)\s*([1-4ivx]{1,3})\s*(?:\/|-|nam\s*)?(20\d{2})?/);if(m){const q=({i:1,ii:2,iii:3,iv:4} as any)[m[1]]||Number(m[1].replace(/[^1-4]/g,""));if(q>=1&&q<=4){year=m[2]?Number(m[2]):year||py;code=`Q${q}-${year}`;type=`Q${q}`}}if(!code&&/(6 thang dau nam|nua dau nam|h1)/.test(t)){year=year||py;code=`H1-${year}`;type="H1"}if(!code&&/(9 thang dau nam|9 thang|9m)/.test(t)){year=year||py;code=`9M-${year}`;type="9M"}if(!code&&/(ca nam|nam tai chinh|fy\s*20\d{2})/.test(t)){year=year||py;code=`FY${year}`;type="FY"}if(!code){m=t.match(/(?:thang|month)\s*(1[0-2]|0?[1-9])(?:\s*\/\s*|\s+)(20\d{2})/);if(m){year=Number(m[2]);code=`M${String(Number(m[1])).padStart(2,"0")}-${year}`;type="MONTH"}}return{code,type,year,confidence:code?90:year?55:20};}
function roleFrom(n:any,context:string){const r=String(n?.role||"").toUpperCase();if(["ACTUAL","FORECAST","PREVIOUS"].includes(r))return r;const t=norm(context);if(/ke hoach|muc tieu/.test(t))return"PLAN";if(/consensus|dong thuan/.test(t))return"CONSENSUS";if(/du bao|ky vong|uoc tinh|forecast|expected/.test(t))return"FORECAST";if(/cung ky|quy truoc|thang truoc|nam truoc|previous|prior/.test(t))return"PREVIOUS";return"OBSERVED"}
function freshness(period:any,role:string,published:string|null){if(["FORECAST","PLAN","CONSENSUS"].includes(role))return"FORWARD_LOOKING";if(!period.code)return"UNKNOWN_PERIOD";const now=new Date(),cy=now.getUTCFullYear(),y=period.year||cy;if(y<cy-1)return"HISTORICAL";if(y===cy-1)return"PREVIOUS";if(y>cy)return"FORWARD_LOOKING";const age=published?(Date.now()-new Date(published).getTime())/86400000:null;if(age!=null&&age>120)return"HISTORICAL";return"CURRENT_OR_RECENT"}
function metricHint(ctx:string,kind:string){const t=norm(ctx);if(/loi nhuan sau thue|lnst|net profit/.test(t))return"NET_PROFIT";if(/loi nhuan truoc thue|lntt|pretax/.test(t))return"PRETAX_PROFIT";if(/doanh thu|revenue/.test(t))return"REVENUE";if(/cpi|lam phat/.test(t))return"CPI";if(/gdp/.test(t))return"GDP";if(/lai suat|interest rate|fed funds/.test(t))return"INTEREST_RATE";if(/ty gia|usd\/vnd|usdvnd/.test(t))return"FX";if(/mua rong|ban rong|khoi ngoai/.test(t))return"FOREIGN_FLOW";return kind||"NUMBER"}
function decorateNumber(n:any,published:string|null){const ctx=clean(n?.context||"");const p=periodFrom(ctx,published),role=roleFrom(n,ctx),fresh=freshness(p,role,published);let conf=Number(p.confidence||0);if(ctx.length>30)conf+=5;if(role!=="OBSERVED")conf+=5;if(fresh==="UNKNOWN_PERIOD")conf-=10;return{metric:metricHint(ctx,String(n?.kind||"NUMBER")),value:n?.value??null,unit:n?.unit??null,role,period:p.code,period_type:p.type,period_year:p.year,freshness:fresh,period_confidence:clamp(conf),context:ctx.slice(0,240)}}
function labelFresh(list:any[]){if(list.some(x=>x.freshness==="CURRENT_OR_RECENT"))return"CÓ SỐ LIỆU GẦN HIỆN TẠI";if(list.some(x=>x.freshness==="FORWARD_LOOKING"))return"CÓ DỮ LIỆU DỰ PHÓNG/KẾ HOẠCH";if(list.some(x=>x.freshness==="UNKNOWN_PERIOD"))return"CẦN KIỂM TRA KỲ SỐ LIỆU";if(list.length)return"DỮ LIỆU LỊCH SỬ";return"KHÔNG CÓ SỐ ĐỊNH LƯỢNG"}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="GET")return res(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);try{
 const since=new Date(Date.now()-26*3600000).toISOString();
 const{data:events,error}=await db.from("news_intelligence_events").select("id,event_title,event_type,canonical_news_item_id,primary_tickers,sectors,source_ids,lineage_keys,article_count,independent_source_count,fact_summary,number_summary,historical_context,expectation,surprise,verification,market_confirmation,vietnam_transmission,impact_score,confidence_score,action_relevance_score,action_label,action_reason,direction,data_quality_score,evidence_quality_score,last_seen_at,last_scored_at").eq("status","ACTIVE").gte("last_seen_at",since).order("last_seen_at",{ascending:false}).limit(300);if(error)throw error;
 const ids=(events||[]).map((e:any)=>e.canonical_news_item_id).filter(Boolean);let rawMap=new Map<string,any>();if(ids.length){const{data:r}=await db.from("news_items_raw").select("id,source_id,title,summary,source_url,published_at,fetched_at").in("id",ids);rawMap=new Map((r||[]).map((x:any)=>[x.id,x]))}
 const sourceIds=[...new Set((events||[]).flatMap((e:any)=>e.source_ids||[]))];let sourceMap=new Map<string,any>();if(sourceIds.length){const{data:s}=await db.from("news_sources").select("source_id,source_name,trust_score,category,group_name").in("source_id",sourceIds);sourceMap=new Map((s||[]).map((x:any)=>[x.source_id,x]))}
 const out=(events||[]).map((e:any)=>{const r=rawMap.get(e.canonical_news_item_id)||{},published=r.published_at||e.last_seen_at||null,nums=(e.number_summary?.observations||[]).slice(-16).map((n:any)=>decorateNumber(n,published));const current=nums.filter((x:any)=>x.freshness==="CURRENT_OR_RECENT"),unknown=nums.filter((x:any)=>x.freshness==="UNKNOWN_PERIOD");const sources=(e.source_ids||[]).slice(0,6).map((id:string)=>{const s=sourceMap.get(id)||{};return{id,name:s.source_name||id,trust_score:s.trust_score??null}});let periodWarning=null;if(unknown.length)periodWarning=`${unknown.length} số liệu chưa xác định chắc kỳ; không nên dùng như số hiện tại.`;else if(nums.length&&!current.length)periodWarning="Chưa có số liệu được xác định là gần hiện tại trong cụm tin này.";return{id:e.id,title:e.event_title,event_type:e.event_type,tickers:e.primary_tickers||[],sectors:e.sectors||[],published_at:published,last_seen_at:e.last_seen_at,source_url:r.source_url||null,source_name:(sourceMap.get(r.source_id)||{}).source_name||r.source_id||null,sources,article_count:e.article_count||1,independent_source_count:e.independent_source_count||1,impact_score:e.impact_score,confidence_score:e.confidence_score,action_relevance_score:e.action_relevance_score,action_label:e.action_label,action_reason:e.action_reason||null,direction:e.direction||null,data_quality_score:e.data_quality_score??null,evidence_quality_score:e.evidence_quality_score??null,market_confirmation:e.market_confirmation||null,verification:e.verification||null,vietnam_transmission:e.vietnam_transmission||null,numbers:nums.slice(0,10),freshness_label:labelFresh(nums),period_warning:periodWarning,summary:clean(r.summary||e.fact_summary?.latest?.[0]?.statement||"").slice(0,360)}});
 out.sort((a:any,b:any)=>new Date(b.published_at||b.last_seen_at||0).getTime()-new Date(a.published_at||a.last_seen_at||0).getTime());
 return res(req,{ok:true,engine:"VÕ HOÀNG NEWS INTELLIGENCE V2 PREVIEW",version:"2.0-all-active-24h",generated_at:new Date().toISOString(),principles:["article_date_is_not_data_period","unknown_period_is_not_current","independent_sources_not_article_count","data_first_narrative_second","no_score_filter_for_24h_list"],events:out,total:out.length});
}catch(e){return res(req,{ok:false,error:"PREVIEW_FAILED",detail:String((e as any)?.message||e).slice(0,500)},500)}});
