import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BRIDGE_KEY=Deno.env.get("VH_BRIDGE_KEY")||"";
const V4_URL=`${SUPABASE_URL}/functions/v1/market-live-narrative-v4`;
const MIN_STOCK_VOLUME=200000;
const SECTOR_REPEAT_MINUTES=45;
const SECTOR_MATERIAL_PP=.75;
const ALLOWED=new Set(["https://vohoanginvest.com","https://www.vohoanginvest.com","https://hoangonthi.github.io"]);

type Focus={headline:string;body:string;watch_next:string};
function cors(req:Request){const o=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://www.vohoanginvest.com","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"content-type,x-bridge-key","Cache-Control":"no-store","Vary":"Origin"};}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}});}
function sh(extra:Record<string,string>={}){return{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,...extra};}
function n(v:any):number|null{if(v===null||v===undefined||v==="")return null;const x=Number(v);return Number.isFinite(x)?x:null;}
function fmt(v:any,d=2){const x=n(v);return x===null?"—":new Intl.NumberFormat("vi-VN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(x);}
function signed(v:any,d=2){const x=n(v);return x===null?"—":`${x>0?"+":""}${fmt(x,d)}`;}
function pct(v:any,d=2){const x=n(v);return x===null?"—":`${signed(x,d)}%`;}
function volText(v:any){const x=n(v);if(x===null)return"—";return x>=1000000?`${fmt(x/1000000,2)} triệu cp`:`${new Intl.NumberFormat("vi-VN",{maximumFractionDigits:0}).format(x)} cp`;}
function vnDate(v:string|Date){const d=v instanceof Date?v:new Date(v);const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const g=(t:string)=>p.find(x=>x.type===t)?.value||"";return`${g("year")}-${g("month")}-${g("day")}`;}
function isLiquidStock(x:any){const v=n(x?.volume);return v!==null&&v>=MIN_STOCK_VOLUME;}
function sectorKey(s:any){return String(s?.key||s?.symbol||s?.name||"").trim();}

async function restGet(path:string){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:sh()});if(!r.ok)return null;return await r.json();}catch{return null;}}
async function restPatch(path:string,row:any){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:"PATCH",headers:sh({"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify(row)});if(!r.ok)return null;const d=await r.json();return Array.isArray(d)?d[0]||null:d;}catch{return null;}}
async function restDelete(path:string){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:"DELETE",headers:sh({"Prefer":"return=minimal"})});return r.ok;}catch{return false;}}

function sectorsOf(payload:any){return Array.isArray(payload?.watchlist_sectors)&&payload.watchlist_sectors.length?payload.watchlist_sectors:(Array.isArray(payload?.market?.sectors)?payload.market.sectors:[]);}
function stockMap(payload:any){const map=new Map<string,any>();for(const s of sectorsOf(payload)){for(const side of ["top_gainers","top_losers"]){for(const x of (Array.isArray(s?.[side])?s[side]:[])){const sym=String(x?.symbol||"").toUpperCase();if(!sym)continue;const row={...x,symbol:sym,sector:s},old=map.get(sym);if(!old||Math.abs(n(x?.change_pct)??0)>Math.abs(n(old?.change_pct)??0))map.set(sym,row);}}}return map;}
function findSector(payload:any,keyOrName:string){const needle=String(keyOrName||"");return sectorsOf(payload).find((s:any)=>sectorKey(s)===needle||String(s?.name||"")===needle)||null;}
function liquidSide(sector:any,side:"top_gainers"|"top_losers"){return (Array.isArray(sector?.[side])?sector[side]:[]).filter(isLiquidStock);}
function currentEventSector(ev:any,payload:any){const w=ev?.facts?.world||{};let raw:any=null;if(String(ev?.event_type||"")==="LEADERSHIP_ROTATION")raw=w?.lines?.strongest?.[0]||null;else raw=w?.driver?.sector||ev?.facts?.sector||w?.lines?.strongest?.[0]||null;if(!raw)return null;return findSector(payload,sectorKey(raw))||findSector(payload,String(raw?.name||""))||raw;}
function eventSectorPct(ev:any){const w=ev?.facts?.world||{};const s=String(ev?.event_type||"")==="LEADERSHIP_ROTATION"?w?.lines?.strongest?.[0]:w?.driver?.sector||ev?.facts?.sector;return n(s?.change_pct);}
function eventSectorKey(ev:any){const w=ev?.facts?.world||{};const s=String(ev?.event_type||"")==="LEADERSHIP_ROTATION"?w?.lines?.strongest?.[0]:w?.driver?.sector||ev?.facts?.sector;return sectorKey(s);}

async function deleteEventArtifacts(eventId:number){const rows=await restGet(`market_live_comments?event_id=eq.${eventId}&select=id`);for(const r of (Array.isArray(rows)?rows:[]))await restDelete(`market_live_comments?id=eq.${Number(r.id)}`);await restDelete(`market_live_events?id=eq.${eventId}`);}
async function deleteComment(commentId:number){if(commentId>0)await restDelete(`market_live_comments?id=eq.${commentId}`);}
async function rewriteComment(eventId:number,patch:Focus,extraEvidence:any={}){const rows=await restGet(`market_live_comments?event_id=eq.${eventId}&select=id,evidence&order=id.desc&limit=1`),c=Array.isArray(rows)?rows[0]||null:null;if(!c?.id)return null;return await restPatch(`market_live_comments?id=eq.${Number(c.id)}`,{headline:patch.headline,body:patch.body,watch_next:patch.watch_next,evidence:{...(c.evidence||{}),router:{...(c.evidence?.router||{}),version:"v5.1",focus_mode:true,min_stock_volume:MIN_STOCK_VOLUME,...extraEvidence}}});}

function focusedStock(ev:any,stock:any,prev:any):Focus{const sector=ev?.facts?.sector||stock?.sector||{},sym=String(stock?.symbol||ev?.facts?.stock?.symbol||"").toUpperCase(),curr=n(stock?.change_pct??ev?.facts?.stock?.change_pct),old=n(prev?.facts?.stock?.change_pct),delta=curr!==null&&old!==null?curr-old:null;let headline=String(ev?.title||`${sym} có biến động đáng chú ý`);if(delta!==null&&delta>=3)headline=`${sym} tăng tốc rõ so với lần nhắc trước`;else if(delta!==null&&delta<=-3)headline=`${sym} hạ nhiệt mạnh so với lần nhắc trước`;const parts:string[]=[];if(curr!==null)parts.push(`${sym} hiện ${pct(curr)}${sector?.name?` trong ${sector.name}`:""}, khối lượng khoảng ${volText(stock?.volume??ev?.facts?.stock?.volume)}.`);if(delta!==null)parts.push(`So với lần nhắc trước, biên độ thay đổi ${signed(delta,2)} điểm phần trăm.`);if(sector?.name&&n(sector?.change_pct)!==null)parts.push(`Toàn nhóm ${sector.name} đang ${pct(sector.change_pct)}${n(sector?.adv)!==null&&n(sector?.dec)!==null?`, ${Math.round(sector.adv)} mã tăng/${Math.round(sector.dec)} mã giảm`:""}.`);return{headline,body:parts.join(" "),watch_next:`Chỉ nhắc lại ${sym} khi biên độ thay đổi đủ lớn hoặc trạng thái đảo chiều; đồng thời nhìn các mã thanh khoản lớn cùng nhóm để kiểm tra độ lan tỏa.`};}

function focusedSector(ev:any,sector:any):Focus{const type=String(ev?.event_type||""),up=liquidSide(sector,"top_gainers"),down=liquidSide(sector,"top_losers"),strong=up.filter((x:any)=>(n(x?.change_pct)??0)>=5);let headline=String(ev?.title||`${sector?.name||"Nhóm ngành"} đang nổi bật`);const parts:string[]=[];if(n(sector?.change_pct)!==null)parts.push(`${sector.name} đang ${pct(sector.change_pct)}${n(sector?.adv)!==null&&n(sector?.dec)!==null?`, với ${Math.round(sector.adv)} mã tăng/${Math.round(sector.dec)} mã giảm`:""}.`);if(strong.length>=2)parts.push(`Trong các mã có khối lượng từ 200.000 cp trở lên, ${strong.slice(0,3).map((x:any)=>`${x.symbol} ${pct(x.change_pct)}`).join(", ")} cùng tăng mạnh.`);else if(up.length)parts.push(`Các mã thanh khoản đủ lớn đang nổi bật: ${up.slice(0,3).map((x:any)=>`${x.symbol} ${pct(x.change_pct)}`).join(", ")}.`);if(down.length&&(n(down[0]?.change_pct)??0)<=-3)parts.push(`Ở chiều ngược lại, ${down.slice(0,2).map((x:any)=>`${x.symbol} ${pct(x.change_pct)}`).join(", ")}.`);if(type==="LEADERSHIP_ROTATION"&&parts.length<2)parts.push("Nhóm vừa cải thiện vị trí tương đối so với nhịp trước.");return{headline,body:parts.join(" "),watch_next:`Theo dõi xem sức mạnh của ${sector?.name||"nhóm này"} có tiếp tục lan sang các mã có thanh khoản lớn hay bắt đầu thu hẹp.`};}

function focusedIndex(ev:any,payload:any):Focus{const type=String(ev?.event_type||""),w=ev?.facts?.world||payload?.world_model||{},b=w?.ball||{},br=w?.match?.breadth||{},v=payload?.market?.vnindex||{},value=n(b?.value)??n(v?.value),change=n(b?.change)??n(v?.change),p=n(b?.pct)??n(v?.change_pct),d5=n(b?.delta_5m),d15=n(b?.delta_15m);let headline=String(ev?.title||"VN-Index đang có thay đổi đáng chú ý"),body="",watch="";
  if(type==="REBOUND_FROM_LOW"){body=`VN-Index đã hồi khoảng ${fmt(n(b?.rebound_from_low),1)} điểm từ đáy phiên và hiện ở ${fmt(value,2)} điểm.`;watch="Nhìn tiếp xem chỉ số có giữ được phần hồi vừa có hay quay lại kiểm định vùng đáy trong phiên.";}
  else if(type==="DROP_FROM_HIGH"){body=`VN-Index đã lùi khoảng ${fmt(n(b?.drop_from_high),1)} điểm từ đỉnh phiên và hiện ở ${fmt(value,2)} điểm.`;watch="Theo dõi xem nhịp lùi chỉ là rung lắc hay tiếp tục mở rộng khỏi vùng đỉnh phiên.";}
  else if(type==="RED_TO_GREEN"||type==="GREEN_TO_RED"){body=`VN-Index hiện ở ${fmt(value,2)} điểm, thay đổi ${signed(change,2)} điểm (${pct(p)}).`;watch="Theo dõi khả năng giữ trạng thái mới trong các nhịp tiếp theo thay vì chỉ nhìn một lần đổi màu.";}
  else if(type.startsWith("CROSS_")){body=`${headline} quanh ${fmt(n(ev?.facts?.level),1)} điểm; chỉ số hiện ở ${fmt(value,2)} điểm.`;watch="Điểm cần nhìn là khả năng giữ được phía vừa vượt qua của vùng kỹ thuật này.";}
  else if(type.startsWith("APPROACH_")){const z=ev?.facts?.zone||{};body=`VN-Index hiện ở ${fmt(value,2)} điểm và đang tiến gần ${z?.label||"vùng kỹ thuật"} quanh ${fmt(n(z?.value),1)} điểm.`;watch="Theo dõi phản ứng của chỉ số ngay tại vùng kỹ thuật này; chưa cần kéo thêm câu chuyện ngành nếu chưa có thay đổi riêng.";}
  else if(type==="STORY_TURN_POSITIVE"||type==="STORY_TURN_NEGATIVE"){body=`VN-Index thay đổi ${signed(d15,2)} điểm trong khoảng 15 phút${d5!==null?`, riêng 5 phút gần đây ${signed(d5,2)} điểm`:""}.`;if(n(br?.adv)!==null&&n(br?.dec)!==null)body+=` Độ rộng đi kèm ${Math.round(br.adv)} mã tăng/${Math.round(br.dec)} mã giảm.`;watch="Theo dõi xem nhịp thay đổi 15 phút có được duy trì ở lần quét kế tiếp hay không.";}
  else if(type==="INDEX_GREEN_BREADTH_WEAK"){body=`VN-Index đang ${pct(p)}, nhưng độ rộng chỉ có ${Math.round(n(br?.adv)??0)} mã tăng so với ${Math.round(n(br?.dec)??0)} mã giảm.`;watch="Nếu độ rộng không cải thiện, điểm số xanh vẫn cần được nhìn thận trọng vì sức mạnh có thể còn tập trung.";}
  else if(type==="MATCH_RECAP"){body=`VN-Index hiện ở ${fmt(value,2)} điểm, ${signed(change,2)} điểm (${pct(p)}).`;if(d5!==null||d15!==null)body+=` Nhịp gần: 5 phút ${signed(d5,2)} điểm, 15 phút ${signed(d15,2)} điểm.`;watch="Chờ thay đổi mới của chính chỉ số trước khi cập nhật lại câu chuyện này.";}
  else {body=`VN-Index hiện ở ${fmt(value,2)} điểm, ${signed(change,2)} điểm (${pct(p)}).`;watch="Theo dõi nhịp kế tiếp của chỉ số và các vùng kỹ thuật gần nhất.";}
  return{headline,body,watch_next:watch};}

function focusedLiquidity(ev:any,payload:any):Focus{const pace=n(ev?.facts?.pace_ratio)??n(payload?.market?.flow?.pace_ratio_15m),valueB=n(payload?.market?.vnindex?.value_b);let body=pace!==null?`Nhịp tiền 15 phút đang ở khoảng ${fmt(pace,2)} lần so với chuẩn so sánh.`:"Dòng tiền 15 phút đang thay đổi đáng chú ý.";if(valueB!==null)body+=` Tổng giá trị giao dịch ghi nhận khoảng ${fmt(valueB,1)} tỷ đồng.`;return{headline:String(ev?.title||"Dòng tiền 15 phút đang thay đổi"),body,watch_next:"Theo dõi xem nhịp tiền có duy trì trong các lần quét tiếp theo hay chỉ tăng tốc ngắn."};}

function previousStockEvent(events:any[],sym:string,currentId:number){return events.find(e=>Number(e?.id)!==currentId&&String(e?.event_type||"").startsWith("STOCK_")&&String(e?.facts?.stock?.symbol||"").toUpperCase()===sym)||null;}
function previousSectorEvent(events:any[],ev:any,currentId:number){const k=eventSectorKey(ev);if(!k)return null;return events.find(e=>Number(e?.id)!==currentId&&["DRIVER_ACCELERATE","LEADERSHIP_ROTATION"].includes(String(e?.event_type||""))&&eventSectorKey(e)===k)||null;}
async function ecosystemRowsFor(sym:string){const rows=await restGet(`market_live_ecosystems?symbol=eq.${encodeURIComponent(sym)}&is_active=eq.true&select=ecosystem_key,ecosystem_name,symbol,relation_label,sort_order&limit=4`);return Array.isArray(rows)?rows:[];}

async function rewriteLoopComment(comment:any,payload:any){const family=String(comment?.evidence?.router?.family||"");if(!comment?.id)return{comment,suppressed:null};const sm=stockMap(payload),v=payload?.market?.vnindex||{},mem=payload?.local_memory||{};
  if(family==="market_chain"){const m5=n(mem?.m5?.value),m15=n(mem?.m15?.value),now=n(v?.value),d5=now!==null&&m5!==null?now-m5:null,d15=now!==null&&m15!==null?now-m15:null;const headline=d5!==null&&Math.abs(d5)>=.5?`VN-Index ${d5>0?"đang nhích lên":"đang lùi lại"} trong 5 phút gần đây`:`VN-Index đang giữ nhịp quanh ${fmt(now,2)} điểm`;let body=`VN-Index hiện ở ${fmt(now,2)} điểm, ${signed(v?.change,2)} điểm (${pct(v?.change_pct)}).`;if(d5!==null||d15!==null)body+=` So với mốc gần: 5 phút ${signed(d5,2)} điểm, 15 phút ${signed(d15,2)} điểm.`;const patched=await restPatch(`market_live_comments?id=eq.${Number(comment.id)}`,{headline,body,watch_next:"Theo dõi chính nhịp của VN-Index và vùng kỹ thuật gần nhất; câu chuyện ngành sẽ được tách thành bình luận riêng khi có thay đổi đáng nói.",evidence:{...(comment.evidence||{}),router:{...(comment.evidence?.router||{}),version:"v5.1",focus_mode:true}}});return{comment:patched||comment,suppressed:null};}
  if(family==="breadth"){const adv=n(v?.adv),dec=n(v?.dec),flat=n(v?.flat);const body=`Độ rộng hiện có ${adv===null?"—":Math.round(adv)} mã tăng, ${dec===null?"—":Math.round(dec)} mã giảm${flat!==null?` và ${Math.round(flat)} mã đứng giá`:""}.`;const patched=await restPatch(`market_live_comments?id=eq.${Number(comment.id)}`,{body,watch_next:"Theo dõi xem số mã tăng/giảm có tiếp tục mở rộng theo cùng một hướng ở lần quét kế tiếp hay không.",evidence:{...(comment.evidence||{}),router:{...(comment.evidence?.router||{}),version:"v5.1",focus_mode:true}}});return{comment:patched||comment,suppressed:null};}
  if(family==="sector_scan"){const sector=[...sectorsOf(payload)].filter((s:any)=>n(s?.change_pct)!==null).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct))[0];if(!sector)return{comment,suppressed:null};const f=focusedSector({title:`${sector.name} đang là nhóm nổi bật`,event_type:"SECTOR_SCAN"},sector),patched=await restPatch(`market_live_comments?id=eq.${Number(comment.id)}`,{headline:f.headline,body:f.body,watch_next:f.watch_next,evidence:{...(comment.evidence||{}),router:{...(comment.evidence?.router||{}),version:"v5.1",focus_mode:true,min_stock_volume:MIN_STOCK_VOLUME}}});return{comment:patched||comment,suppressed:null};}
  if(family==="hot_stocks"){const sym=String(comment?.evidence?.hot_stock?.symbol||"").toUpperCase(),stock=sm.get(sym);if(!stock||!isLiquidStock(stock)){await deleteComment(Number(comment.id));return{comment:null,suppressed:{family,symbol:sym,reason:"VOLUME_BELOW_200K_OR_UNKNOWN"}};}const h=comment?.evidence?.hot_stock||{};const body=`${sym} đang nằm trong danh sách cổ phiếu đáng chú ý hôm nay, thay đổi ${pct(stock.change_pct)}, khối lượng khoảng ${volText(stock.volume)}${n(h?.t_score)!==null?`, T-score ${Math.round(h.t_score)}/100`:""}.`;const patched=await restPatch(`market_live_comments?id=eq.${Number(comment.id)}`,{body,watch_next:`Theo dõi riêng ${sym}: tín hiệu chỉ đáng giữ trong câu chuyện nếu thanh khoản và biến động tiếp tục xác nhận.`,evidence:{...(comment.evidence||{}),router:{...(comment.evidence?.router||{}),version:"v5.1",focus_mode:true,min_stock_volume:MIN_STOCK_VOLUME}}});return{comment:patched||comment,suppressed:null};}
  if(family==="flow_scan"){const top=Array.isArray(comment?.evidence?.top_value)?comment.evidence.top_value:[],verified=top.map((x:any)=>({meta:x,stock:sm.get(String(x?.symbol||"").toUpperCase())})).filter((x:any)=>x.stock&&isLiquidStock(x.stock));if(verified.length<2){await deleteComment(Number(comment.id));return{comment:null,suppressed:{family,reason:"NOT_ENOUGH_200K_VOLUME_STOCKS"}};}const body=`Dòng tiền ngắn hạn đang tập trung ở ${verified.slice(0,3).map((x:any)=>`${x.stock.symbol} ${pct(x.stock.change_pct)}`).join(" · ")}. Các mã này đều đã giao dịch từ 200.000 cp trở lên.`;const patched=await restPatch(`market_live_comments?id=eq.${Number(comment.id)}`,{body,watch_next:"Theo dõi xem nhóm mã có dòng tiền nổi bật có mở rộng thêm hay thu hẹp trong nhịp tiếp theo.",evidence:{...(comment.evidence||{}),router:{...(comment.evidence?.router||{}),version:"v5.1",focus_mode:true,min_stock_volume:MIN_STOCK_VOLUME}}});return{comment:patched||comment,suppressed:null};}
  if(family==="ecosystem"){const m=String(comment?.headline||"").match(/^([A-Z][A-Z0-9]{1,5})\b/),sym=m?.[1]||"",stock=sm.get(sym);if(!stock||!isLiquidStock(stock)){await deleteComment(Number(comment.id));return{comment:null,suppressed:{family,symbol:sym,reason:"VOLUME_BELOW_200K_OR_UNKNOWN"}};}const rel=await ecosystemRowsFor(sym),primary=rel[0];if(primary){const group=await restGet(`market_live_ecosystems?ecosystem_key=eq.${encodeURIComponent(primary.ecosystem_key)}&is_active=eq.true&select=symbol,ecosystem_name,relation_label,sort_order&order=sort_order.asc`),peers=(Array.isArray(group)?group:[]).map((r:any)=>sm.get(String(r.symbol||"").toUpperCase())).filter((x:any)=>x&&String(x.symbol)!==sym&&isLiquidStock(x)).slice(0,3);let body=`${sym} hiện ${pct(stock.change_pct)}, khối lượng khoảng ${volText(stock.volume)}. Đây là mã thuộc hệ ${primary.ecosystem_name}.`;if(peers.length)body+=` Các mã cùng hệ có thanh khoản đủ lớn đang có dữ liệu: ${peers.map((x:any)=>`${x.symbol} ${pct(x.change_pct)}`).join(", ")}.`;const patched=await restPatch(`market_live_comments?id=eq.${Number(comment.id)}`,{body,watch_next:`Đối chiếu ${sym} với các mã cùng hệ có thanh khoản đủ lớn để xem chuyển động đang lan tỏa hay chỉ tập trung ở một mã.`,evidence:{...(comment.evidence||{}),router:{...(comment.evidence?.router||{}),version:"v5.1",focus_mode:true,min_stock_volume:MIN_STOCK_VOLUME}}});return{comment:patched||comment,suppressed:null};}}
  return{comment,suppressed:null};}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);const key=req.headers.get("x-bridge-key")||"";if(!BRIDGE_KEY||key!==BRIDGE_KEY)return json(req,{ok:false,error:"UNAUTHORIZED"},401);let input:any;try{input=await req.json();}catch{return json(req,{ok:false,error:"INVALID_JSON"},400);}if(!input?.ok)return json(req,{ok:false,error:"INVALID_PAYLOAD"},400);
  let upstream:any;try{const r=await fetch(V4_URL,{method:"POST",headers:{"Content-Type":"application/json; charset=utf-8","x-bridge-key":key},body:JSON.stringify(input)}),text=await r.text();try{upstream=JSON.parse(text);}catch{upstream={ok:false,error:"V4_BAD_JSON",detail:text.slice(0,300)}}if(!r.ok)return json(req,{...upstream,focus_router:{version:"v5.1",stage:"v4",status:r.status}},r.status);}catch(e){return json(req,{ok:false,error:"V4_UNAVAILABLE",detail:String((e as Error)?.message||e).slice(0,240)},502);}
  const capturedAt=typeof input?.captured_at==="string"&&!Number.isNaN(new Date(input.captured_at).getTime())?new Date(input.captured_at).toISOString():new Date().toISOString(),marketDate=vnDate(capturedAt);
  const [curRows,events]=await Promise.all([restGet(`market_live_current?id=eq.vietnam&market_date=eq.${marketDate}&select=payload&limit=1`),restGet(`market_live_events?market_date=eq.${marketDate}&select=id,detected_at,event_type,title,facts&order=id.desc&limit=100`)]);const payload=Array.isArray(curRows)?curRows[0]?.payload||null:null,eventRows=Array.isArray(events)?events:[];let published=upstream?.published_comment||null,event=upstream?.event||null,suppressed:any=null,rewritten=false;
  if(event?.id&&payload){const ev=eventRows.find((x:any)=>Number(x.id)===Number(event.id))||null,type=String(ev?.event_type||"");
    if(ev&&type.startsWith("STOCK_")){const sym=String(ev?.facts?.stock?.symbol||"").toUpperCase(),sm=stockMap(payload),stock=sm.get(sym)||ev?.facts?.stock,vol=n(stock?.volume);if(vol===null||vol<MIN_STOCK_VOLUME){await deleteEventArtifacts(Number(ev.id));published=null;event=null;suppressed={type,symbol:sym,reason:"VOLUME_BELOW_200K_OR_UNKNOWN",volume:vol,min_volume:MIN_STOCK_VOLUME};}else{const prev=previousStockEvent(eventRows,sym,Number(ev.id)),focus=focusedStock(ev,stock,prev),patched=await rewriteComment(Number(ev.id),focus,{story_family:"stock",stock_symbol:sym,volume:vol});published=patched||published;rewritten=Boolean(patched);}}
    else if(ev&&["DRIVER_ACCELERATE","LEADERSHIP_ROTATION"].includes(type)){const sector=currentEventSector(ev,payload),prev=previousSectorEvent(eventRows,ev,Number(ev.id)),currPct=n(sector?.change_pct)??eventSectorPct(ev),prevPct=prev?eventSectorPct(prev):null,age=prev?new Date(capturedAt).getTime()-new Date(prev.detected_at).getTime():Infinity;if(prev&&age<SECTOR_REPEAT_MINUTES*60000&&currPct!==null&&prevPct!==null&&Math.abs(currPct-prevPct)<SECTOR_MATERIAL_PP){await deleteEventArtifacts(Number(ev.id));published=null;event=null;suppressed={type,sector:sector?.name||eventSectorKey(ev),reason:"SECTOR_STORY_NOT_MATERIAL_ENOUGH",change_pp:Math.round(Math.abs(currPct-prevPct)*1000)/1000,repeat_minutes:SECTOR_REPEAT_MINUTES};}else if(sector){const focus=focusedSector(ev,sector),patched=await rewriteComment(Number(ev.id),focus,{story_family:"sector",sector_key:sectorKey(sector),sector_change_pct:currPct});published=patched||published;rewritten=Boolean(patched);}}
    else if(ev&&["REBOUND_FROM_LOW","DROP_FROM_HIGH","RED_TO_GREEN","GREEN_TO_RED","STORY_TURN_POSITIVE","STORY_TURN_NEGATIVE","INDEX_GREEN_BREADTH_WEAK","MATCH_RECAP"].includes(type)||ev&&type.startsWith("CROSS_")||ev&&type.startsWith("APPROACH_")){const focus=focusedIndex(ev,payload),patched=await rewriteComment(Number(ev.id),focus,{story_family:"index"});published=patched||published;rewritten=Boolean(patched);}
    else if(ev&&type==="LIQUIDITY_ACCELERATE"){const focus=focusedLiquidity(ev,payload),patched=await rewriteComment(Number(ev.id),focus,{story_family:"liquidity"});published=patched||published;rewritten=Boolean(patched);}
  }
  if(published&&published.event_id==null&&payload){const r=await rewriteLoopComment(published,payload);published=r.comment;if(r.suppressed)suppressed=r.suppressed;if(r.comment!==upstream?.published_comment)rewritten=true;}
  return json(req,{...upstream,engine:"market-live-commentary-focus-v5.1",published_comment:published,event,focus_router:{version:"v5.1",min_stock_volume:MIN_STOCK_VOLUME,sector_repeat_minutes:SECTOR_REPEAT_MINUTES,sector_material_pp:SECTOR_MATERIAL_PP,suppressed,rewritten,rule:"one comment = one main story; stock mentions require >=200k shares; index, sector, stock, breadth, derivatives and liquidity are narrated as separate stories"}});
});
