import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BRIDGE_KEY = Deno.env.get("VH_BRIDGE_KEY") || "";

const ALLOWED_ORIGINS = new Set([
  "https://vohoanginvest.com",
  "https://www.vohoanginvest.com",
  "https://hoangonthi.github.io"
]);

function cors(req: Request) {
  const origin = req.headers.get("origin") || "";
  return {
    "Access-Control-Allow-Origin": ALLOWED_ORIGINS.has(origin) ? origin : "https://www.vohoanginvest.com",
    "Access-Control-Allow-Methods": "POST,OPTIONS",
    "Access-Control-Allow-Headers": "content-type,x-bridge-key",
    "Cache-Control": "no-store",
    "Vary": "Origin"
  };
}
function json(req: Request, body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...cors(req), "Content-Type": "application/json; charset=utf-8" } });
}
function serviceHeaders(extra: Record<string,string>={}) { return { apikey:SERVICE_ROLE_KEY, Authorization:`Bearer ${SERVICE_ROLE_KEY}`, ...extra }; }
function n(value: unknown): number | null { const x=Number(value); return Number.isFinite(x)?x:null; }
function first(obj:any, keys:string[]) { for(const key of keys){ const value=key.split(".").reduce((a,b)=>a?.[b],obj); if(value!==undefined&&value!==null&&value!=="") return value;} return null; }
function round(value:number,digits=2){const p=10**digits;return Math.round(value*p)/p;}
function vnDate(value:string|Date){const d=value instanceof Date?value:new Date(value);const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const get=(t:string)=>parts.find(p=>p.type===t)?.value||"";return `${get("year")}-${get("month")}-${get("day")}`;}
function marketIndex(context:any,symbol:string){return Array.isArray(context?.indexes)?context.indexes.find((x:any)=>String(x?.symbol||"").toUpperCase()===symbol.toUpperCase())||null:null;}

function normalize(input:any){
  const t=input?.technical||{}; const ctx=input?.market_context||{}; const idx=marketIndex(ctx,"VN-INDEX")||{}; const mi=ctx?.market_intelligence||{};
  const reference=n(first(t,["reference","ref","prev_close"]))??n(first(idx,["reference","ref","prev_close"]));
  const value=n(first(t,["value","last","close"]))??n(first(idx,["value","close","last"]));
  const change=n(first(t,["change","change_point"]))??n(first(idx,["change","change_point"]));
  let pct=n(first(t,["change_pct","pct"]))??n(first(idx,["change_pct","pct"]));
  if(pct===null&&value!==null&&reference!==null&&reference!==0)pct=(value/reference-1)*100;
  const high=n(first(t,["high","session_high"]))??n(first(idx,["high"]));
  const low=n(first(t,["low","session_low"]))??n(first(idx,["low"]));
  const rebound=n(first(t,["rebound_from_low"]))??(value!==null&&low!==null?value-low:null);
  const drop=n(first(t,["drop_from_high"]))??(value!==null&&high!==null?high-value:null);
  const adv=n(first(idx,["adv"]))??n(first(mi,["breadth.adv"])); const flat=n(first(idx,["flat"]))??n(first(mi,["breadth.flat"])); const dec=n(first(idx,["dec"]))??n(first(mi,["breadth.dec"]));
  const total=[adv,flat,dec].every(x=>x!==null)?adv!+flat!+dec!:null;
  const balance=total&&total>0?(adv!-dec!)/total:n(first(mi,["breadth.balance"]));
  const sectors=Array.isArray(mi?.sectors)?mi.sectors:[];
  const vn30Stocks=Array.isArray(ctx?.vn30_stocks)?ctx.vn30_stocks:Array.isArray(ctx?.vn30?.stocks)?ctx.vn30.stocks:[];
  return {technical:t,market:{vnindex:{value,reference,change,change_pct:pct,high,low,rebound_from_low:rebound,drop_from_high:drop,adv,flat,dec,breadth_balance:balance,value_b:n(first(idx,["value_b","total_value_b"]))??n(first(mi,["flow.value_b"]))},state:mi?.state||null,breadth:mi?.breadth||null,flow:mi?.flow||null,sectors,alerts:Array.isArray(mi?.alerts)?mi.alerts:[]},vn30_stocks:vn30Stocks,context_received_at:first(ctx,["relay_received_at","received_at","updated_at"]),technical_available:Boolean(input?.technical_available??Object.keys(t).length)};
}
function metrics(payload:any){const v=payload?.market?.vnindex||{};const t=payload?.technical||{};return {value:n(v.value),reference:n(v.reference),change:n(v.change),pct:n(v.change_pct),high:n(v.high),low:n(v.low),rebound:n(v.rebound_from_low),drop:n(v.drop_from_high),adv:n(v.adv),flat:n(v.flat),dec:n(v.dec),breadth:n(v.breadth_balance),valueB:n(v.value_b),ma10:n(first(t,["ma10","ma10_daily"])),ma20:n(first(t,["ma20","ma20_daily"])),ma50:n(first(t,["ma50","ma50_daily"])),vwap:n(first(t,["vwap"])),rsi14:n(first(t,["rsi14","rsi"])),macd:n(first(t,["macd"])),signal:n(first(t,["macd_signal","signal"])),support:n(first(t,["support_near","support"])),resistance:n(first(t,["resistance_near","resistance"]))};}
function sign(x:number|null){if(x===null||Math.abs(x)<0.01)return 0;return x>0?1:-1;}
function crossedUp(cur:number|null,prev:number|null,prev2:number|null,l0:number|null,l1:number|null,l2:number|null){return cur!==null&&prev!==null&&prev2!==null&&l0!==null&&l1!==null&&l2!==null&&cur>=l0&&prev>=l1&&prev2<l2;}
function crossedDown(cur:number|null,prev:number|null,prev2:number|null,l0:number|null,l1:number|null,l2:number|null){return cur!==null&&prev!==null&&prev2!==null&&l0!==null&&l1!==null&&l2!==null&&cur<=l0&&prev<=l1&&prev2>l2;}
type Candidate={type:string;key:string;severity:number;tone:string;title:string;facts:any};
function findPast(rows:any[],capturedAt:string,minutes:number){const target=new Date(capturedAt).getTime()-minutes*60000;let best:any=null,bestDiff=Infinity;for(const row of rows){const diff=Math.abs(new Date(row.captured_at).getTime()-target);if(diff<bestDiff&&diff<=180000){best=row;bestDiff=diff;}}return best;}
function topSector(payload:any){const rows=Array.isArray(payload?.market?.sectors)?[...payload.market.sectors]:[];return rows.filter((x:any)=>n(x?.change_pct)!==null).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct))[0]||null;}
function detect(payload:any,previousRows:any[],capturedAt:string):Candidate[]{
  const cur=metrics(payload),p1=previousRows[0]?metrics(previousRows[0].payload):null,p2=previousRows[1]?metrics(previousRows[1].payload):null,c:Candidate[]=[];
  if(!p1){c.push({type:"SESSION_BASELINE",key:"baseline",severity:1,tone:"neutral",title:"Bắt đầu theo dõi diễn biến trong phiên",facts:{current:cur}});return c;}
  if(p2){const s0=sign(cur.change??(cur.value!==null&&cur.reference!==null?cur.value-cur.reference:null)),s1=sign(p1.change??(p1.value!==null&&p1.reference!==null?p1.value-p1.reference:null)),s2=sign(p2.change??(p2.value!==null&&p2.reference!==null?p2.value-p2.reference:null));if(s0>0&&s1>0&&s2<0)c.push({type:"RED_TO_GREEN",key:"red-to-green",severity:4,tone:"positive",title:"VN-Index quay lại sắc xanh",facts:{current:cur,previous:p1}});if(s0<0&&s1<0&&s2>0)c.push({type:"GREEN_TO_RED",key:"green-to-red",severity:4,tone:"danger",title:"VN-Index chuyển lại sắc đỏ",facts:{current:cur,previous:p1}});for(const [name,label] of [["ma10","MA10"],["ma20","MA20"],["vwap","VWAP"]] as const){if(crossedUp(cur.value,p1.value,p2.value,cur[name],p1[name],p2[name]))c.push({type:`CROSS_${name.toUpperCase()}_UP`,key:`${name}-up`,severity:name==="ma20"?4:3,tone:"positive",title:`VN-Index lấy lại ${label}`,facts:{current:cur,level_name:label,level:cur[name]}});if(crossedDown(cur.value,p1.value,p2.value,cur[name],p1[name],p2[name]))c.push({type:`CROSS_${name.toUpperCase()}_DOWN`,key:`${name}-down`,severity:name==="ma20"?4:3,tone:"warning",title:`VN-Index mất ${label}`,facts:{current:cur,level_name:label,level:cur[name]}});}}
  for(const threshold of [10,7,4]){if(cur.rebound!==null&&p1.rebound!==null&&cur.rebound>=threshold&&p1.rebound<threshold){c.push({type:"REBOUND_FROM_LOW",key:`rebound-${threshold}`,severity:threshold>=7?4:3,tone:"positive",title:`VN-Index hồi ${threshold} điểm từ đáy phiên`,facts:{current:cur,threshold}});break;}}
  for(const threshold of [10,7,4]){if(cur.drop!==null&&p1.drop!==null&&cur.drop>=threshold&&p1.drop<threshold){c.push({type:"DROP_FROM_HIGH",key:`drop-${threshold}`,severity:threshold>=7?4:3,tone:"warning",title:`VN-Index lùi ${threshold} điểm từ đỉnh phiên`,facts:{current:cur,threshold}});break;}}
  const past15=findPast(previousRows,capturedAt,15);if(past15){const m15=metrics(past15.payload);if(cur.breadth!==null&&m15.breadth!==null){const delta=cur.breadth-m15.breadth;if(delta>=0.16)c.push({type:"BREADTH_IMPROVE",key:"breadth-improve",severity:3,tone:"positive",title:"Độ rộng thị trường cải thiện rõ",facts:{current:cur,before:m15,delta:round(delta,3)}});if(delta<=-0.16)c.push({type:"BREADTH_WORSEN",key:"breadth-worsen",severity:3,tone:"warning",title:"Độ rộng thị trường xấu đi",facts:{current:cur,before:m15,delta:round(delta,3)}});}const topNow=topSector(payload),topBefore=topSector(past15.payload);if(topNow&&topBefore&&String(topNow.name)!==String(topBefore.name)&&Number(topNow.change_pct)>=0.5)c.push({type:"SECTOR_LEADER_CHANGE",key:`leader-${String(topNow.symbol||topNow.name)}`,severity:2,tone:"neutral",title:`${topNow.name} vươn lên dẫn dắt`,facts:{current:cur,sector:topNow,previous_sector:topBefore}});}
  if(cur.pct!==null&&cur.breadth!==null){const prevCondition=p1.pct!==null&&p1.breadth!==null&&p1.pct>=0&&p1.breadth<=-0.12;if(cur.pct>=0&&cur.breadth<=-0.12&&!prevCondition)c.push({type:"INDEX_GREEN_BREADTH_WEAK",key:"green-breadth-weak",severity:4,tone:"warning",title:"Chỉ số xanh nhưng độ rộng vẫn yếu",facts:{current:cur}});}
  const pace=n(first(payload,["market.flow.pace_ratio_15m"])),prevPace=n(first(previousRows[0]?.payload,["market.flow.pace_ratio_15m"]));if(pace!==null&&pace>=1.35&&(prevPace===null||prevPace<1.2))c.push({type:"LIQUIDITY_ACCELERATE",key:"liquidity-accelerate",severity:2,tone:"neutral",title:"Dòng tiền trong phiên đang tăng tốc",facts:{current:cur,pace_ratio:round(pace,2)}});
  return c.sort((a,b)=>b.severity-a.severity);
}
function fmt(x:number|null,digits=2){if(x===null)return "—";return new Intl.NumberFormat("vi-VN",{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(x);}function signed(x:number|null,digits=2){if(x===null)return "—";return `${x>0?"+":""}${fmt(x,digits)}`;}
function breadthSentence(cur:any){if(cur.adv===null||cur.dec===null)return "";if(cur.adv>cur.dec*1.25)return `Độ rộng nghiêng tích cực với ${Math.round(cur.adv)} mã tăng so với ${Math.round(cur.dec)} mã giảm.`;if(cur.dec>cur.adv*1.25)return `Độ rộng còn yếu với ${Math.round(cur.dec)} mã giảm so với ${Math.round(cur.adv)} mã tăng.`;return `Độ rộng khá cân bằng: ${Math.round(cur.adv)} mã tăng và ${Math.round(cur.dec)} mã giảm.`;}
function supportText(payload:any){const cur=metrics(payload);if(cur.resistance!==null&&cur.value!==null&&cur.resistance>cur.value&&(cur.resistance/cur.value-1)<=0.012)return `Theo dõi phản ứng của chỉ số khi tiến gần vùng cản ${fmt(cur.resistance,1)} điểm, đồng thời nhìn xem độ rộng và dòng tiền có tiếp tục cải thiện hay không.`;if(cur.support!==null&&cur.value!==null&&cur.support<cur.value&&(cur.value/cur.support-1)<=0.012)return `Theo dõi khả năng giữ vùng hỗ trợ ${fmt(cur.support,1)} điểm cùng diễn biến độ rộng và nhóm dẫn dắt.`;return "Theo dõi tiếp độ rộng, dòng tiền và sức mạnh của nhóm dẫn dắt để xem thay đổi hiện tại có được duy trì hay không.";}
function leaders(payload:any){const sectors=Array.isArray(payload?.market?.sectors)?payload.market.sectors:[];const top=[...sectors].filter((x:any)=>n(x?.change_pct)!==null).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct))[0];const stocks=Array.isArray(payload?.vn30_stocks)?payload.vn30_stocks:[];const gainers=[...stocks].filter((x:any)=>(n(first(x,["change_pct","changePct","pct"]))??0)>0).sort((a:any,b:any)=>Number(first(b,["change_pct","changePct","pct"]))-Number(first(a,["change_pct","changePct","pct"]))).slice(0,3);return {topSector:top||null,gainers};}
function makeComment(candidate:Candidate,payload:any){const cur=metrics(payload),lead=leaders(payload),breadth=breadthSentence(cur),sectorPart=lead.topSector?`${lead.topSector.name} đang là nhóm nổi bật với ${signed(n(lead.topSector.change_pct))}%.`:"",vn30Part=lead.gainers.length?` Trong VN30, ${lead.gainers.map((x:any)=>String(x.symbol||x.code||"")).filter(Boolean).join(", ")} đang tăng và góp phần nâng đỡ nhóm vốn hóa lớn.`:"";let body="";switch(candidate.type){case"SESSION_BASELINE":body=`VN-Index hiện ở ${fmt(cur.value,2)} điểm${cur.change!==null?`, ${signed(cur.change)} điểm`:""}. ${breadth} ${sectorPart}`;break;case"RED_TO_GREEN":{const lowChange=cur.low!==null&&cur.reference!==null?cur.low-cur.reference:null;body=`VN-Index đã quay lại sắc xanh${lowChange!==null&&lowChange<0?` sau khi có lúc giảm ${fmt(Math.abs(lowChange),2)} điểm`:""}. ${cur.rebound!==null?`Từ đáy phiên, chỉ số đã hồi khoảng ${fmt(cur.rebound,2)} điểm.`:""} ${breadth} ${sectorPart}${vn30Part}`;break;}case"GREEN_TO_RED":body=`VN-Index đã chuyển lại sắc đỏ sau nhịp giữ trên tham chiếu. ${cur.drop!==null?`Chỉ số hiện thấp hơn đỉnh phiên khoảng ${fmt(cur.drop,2)} điểm.`:""} ${breadth} ${sectorPart}`;break;case"REBOUND_FROM_LOW":body=`VN-Index đang hồi rõ từ vùng thấp nhất phiên; mức hồi hiện khoảng ${fmt(cur.rebound,2)} điểm. ${breadth} ${sectorPart}${vn30Part}`;break;case"DROP_FROM_HIGH":body=`VN-Index đã lùi khoảng ${fmt(cur.drop,2)} điểm từ đỉnh phiên. ${breadth} ${sectorPart}`;break;case"BREADTH_IMPROVE":body=`Số mã tăng đang cải thiện so với khoảng 15 phút trước. ${breadth} ${sectorPart} Đây là tín hiệu tốt hơn việc chỉ nhìn riêng điểm số VN-Index.`;break;case"BREADTH_WORSEN":body=`Độ rộng đang xấu đi so với khoảng 15 phút trước. ${breadth} Diễn biến bên dưới mặt bằng cổ phiếu cần được chú ý nhiều hơn điểm số chỉ số.`;break;case"INDEX_GREEN_BREADTH_WEAK":body=`VN-Index đang giữ được sắc xanh nhưng số mã giảm vẫn áp đảo. Phần lớn cổ phiếu chưa khỏe tương ứng với điểm số của chỉ số.${vn30Part}`;break;case"SECTOR_LEADER_CHANGE":body=`${candidate.facts?.sector?.name||"Một nhóm ngành"} đã vươn lên dẫn dắt với mức tăng ${signed(n(candidate.facts?.sector?.change_pct))}%. ${breadth} Cần nhìn thêm khả năng lan tỏa sang các nhóm còn lại.`;break;case"LIQUIDITY_ACCELERATE":body=`Tốc độ giao dịch 15 phút gần nhất đang tăng lên so với nhịp trước. ${breadth} ${sectorPart} Cần quan sát dòng tiền tăng tốc đi cùng giá hay đi cùng áp lực bán.`;break;default:{const level=n(candidate.facts?.level),up=candidate.type.endsWith("_UP");body=`VN-Index đã ${up?"đứng trở lại trên":"lùi xuống dưới"} ${candidate.facts?.level_name||"mốc kỹ thuật"}${level!==null?` tại khoảng ${fmt(level,2)} điểm`:""}. ${breadth} ${sectorPart}`;}}
  return {tone:candidate.tone,headline:candidate.title,body:body.replace(/\s+/g," ").trim(),watch_next:supportText(payload),evidence:{vnindex:cur,top_sector:lead.topSector,vn30_gainers:lead.gainers,event_facts:candidate.facts}};
}
async function rest(path:string,init:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...serviceHeaders(),...(init.headers||{})}});}async function wasRecent(date:string,candidate:Candidate){const since=new Date(Date.now()-300000).toISOString();const r=await rest(`market_live_events?market_date=eq.${date}&event_type=eq.${encodeURIComponent(candidate.type)}&event_key=eq.${encodeURIComponent(candidate.key)}&detected_at=gte.${encodeURIComponent(since)}&select=id&limit=1`);if(!r.ok)return false;try{return(await r.json()).length>0}catch{return false}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);if(!BRIDGE_KEY||req.headers.get("x-bridge-key")!==BRIDGE_KEY)return json(req,{ok:false,error:"UNAUTHORIZED"},401);let input:any;try{input=await req.json()}catch{return json(req,{ok:false,error:"INVALID_JSON"},400)}if(!input?.ok)return json(req,{ok:false,error:"INVALID_PAYLOAD"},400);const capturedAt=input?.captured_at?new Date(input.captured_at).toISOString():new Date().toISOString(),marketDate=vnDate(capturedAt),payload=normalize(input);if(metrics(payload).value===null)return json(req,{ok:false,error:"VNINDEX_MISSING"},400);const prevResp=await rest(`market_live_snapshots?market_date=eq.${marketDate}&select=id,captured_at,payload&order=captured_at.desc&limit=140`);let previousRows:any[]=[];if(prevResp.ok){try{previousRows=await prevResp.json()}catch{}}const snapshotResp=await rest("market_live_snapshots",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({market_date:marketDate,captured_at:capturedAt,source_updated_at:input?.source_updated_at||null,source:input?.source||"amibroker-live",payload})});if(!snapshotResp.ok)return json(req,{ok:false,error:"SNAPSHOT_STORE_FAILED",detail:await snapshotResp.text()},500);const snapshotRows=await snapshotResp.json(),snapshotId=snapshotRows?.[0]?.id,candidates=detect(payload,previousRows,capturedAt);let published:any=null;for(const candidate of candidates){if(await wasRecent(marketDate,candidate))continue;const eventResp=await rest("market_live_events",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({market_date:marketDate,snapshot_id:snapshotId,detected_at:capturedAt,event_type:candidate.type,event_key:candidate.key,severity:candidate.severity,tone:candidate.tone,title:candidate.title,facts:candidate.facts})});if(!eventResp.ok)continue;const eventId=(await eventResp.json())?.[0]?.id,comment=makeComment(candidate,payload),commentResp=await rest("market_live_comments",{method:"POST",headers:{"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({market_date:marketDate,published_at:capturedAt,event_id:eventId,snapshot_id:snapshotId,tone:comment.tone,headline:comment.headline,body:comment.body,watch_next:comment.watch_next,evidence:comment.evidence,source_mode:"template-v1"})});if(commentResp.ok){published=(await commentResp.json())?.[0]||null;break;}}return json(req,{ok:true,snapshot_id:snapshotId,captured_at:capturedAt,event_candidates:candidates.map(x=>x.type),published_comment:published?{id:published.id,headline:published.headline}:null});});