import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.48.1";

const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(U,K,{auth:{persistSession:false}});
const ALLOWED=new Set(["https://www.vohoanginvest.com","https://vohoanginvest.com","https://hoangonthi.github.io","http://localhost:5500","http://127.0.0.1:5500"]);
function cors(req:Request){const o=req.headers.get("origin")||"";return{"access-control-allow-origin":ALLOWED.has(o)?o:"https://www.vohoanginvest.com","vary":"Origin","access-control-allow-methods":"GET,OPTIONS","access-control-allow-headers":"content-type","content-type":"application/json; charset=utf-8","cache-control":"public, max-age=60, s-maxage=180"}}
const res=(req:Request,b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors(req)});
const clean=(s:any)=>String(s||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const norm=(s:any)=>clean(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const clamp=(n:number)=>Math.min(100,Math.max(0,Math.round(n)));
function periodFrom(text:string,published:string|null){const t=norm(text),pub=published?new Date(published):null,py=pub&&!isNaN(pub.getTime())?pub.getUTCFullYear():new Date().getUTCFullYear();let year:number|null=null;const ym=t.match(/\b(20\d{2})\b/);if(ym)year=Number(ym[1]);let code:string|null=null,type:string|null=null;let m=t.match(/(?:quy|q)\s*([1-4ivx]{1,3})\s*(?:\/|-|nam\s*)?(20\d{2})?/);if(m){const q=({i:1,ii:2,iii:3,iv:4} as any)[m[1]]||Number(m[1].replace(/[^1-4]/g,""));if(q>=1&&q<=4){year=m[2]?Number(m[2]):year||py;code=`Q${q}-${year}`;type=`Q${q}`}}if(!code&&/(6 thang dau nam|nua dau nam|h1)/.test(t)){year=year||py;code=`H1-${year}`;type="H1"}if(!code&&/(9 thang dau nam|9 thang|9m)/.test(t)){year=year||py;code=`9M-${year}`;type="9M"}if(!code&&/(ca nam|nam tai chinh|fy\s*20\d{2})/.test(t)){year=year||py;code=`FY${year}`;type="FY"}if(!code){m=t.match(/(?:thang|month)\s*(1[0-2]|0?[1-9])(?:\s*\/\s*|\s+)(20\d{2})/);if(m){year=Number(m[2]);code=`M${String(Number(m[1])).padStart(2,"0")}-${year}`;type="MONTH"}}return{code,type,year,confidence:code?90:year?55:20};}
function roleFrom(n:any,context:string){const r=String(n?.role||"").toUpperCase();if(["ACTUAL","FORECAST","PREVIOUS"].includes(r))return r;const t=norm(context);if(/ke hoach|muc tieu/.test(t))return"PLAN";if(/consensus|dong thuan/.test(t))return"CONSENSUS";if(/du bao|ky vong|uoc tinh|forecast|expected/.test(t))return"FORECAST";if(/cung ky|quy truoc|thang truoc|nam truoc|previous|prior/.test(t))return"PREVIOUS";return"OBSERVED"}
function freshness(period:any,role:string,published:string|null){if(["FORECAST","PLAN","CONSENSUS"].includes(role))return"FORWARD_LOOKING";if(!period.code)return"UNKNOWN_PERIOD";const now=new Date(),cy=now.getUTCFullYear(),y=period.year||cy;if(y<cy-1)return"HISTORICAL";if(y===cy-1)return"PREVIOUS";if(y>cy)return"FORWARD_LOOKING";const age=published?(Date.now()-new Date(published).getTime())/86400000:null;if(age!=null&&age>120)return"HISTORICAL";return"CURRENT_OR_RECENT"}
function metricHint(ctx:string,kind:string){const t=norm(ctx);if(/loi nhuan sau thue|lnst|net profit/.test(t))return"NET_PROFIT";if(/loi nhuan truoc thue|lntt|pretax/.test(t))return"PRETAX_PROFIT";if(/doanh thu|revenue/.test(t))return"REVENUE";if(/cpi|lam phat/.test(t))return"CPI";if(/gdp/.test(t))return"GDP";if(/lai suat|interest rate|fed funds/.test(t))return"INTEREST_RATE";if(/ty gia|usd\/vnd|usdvnd/.test(t))return"FX";if(/mua rong|ban rong|khoi ngoai/.test(t))return"FOREIGN_FLOW";return kind||"NUMBER"}
function decorateNumber(n:any,published:string|null){const ctx=clean(n?.context||"");const p=periodFrom(ctx,published),role=roleFrom(n,ctx),fresh=freshness(p,role,published);let conf=Number(p.confidence||0);if(ctx.length>30)conf+=5;if(role!=="OBSERVED")conf+=5;if(fresh==="UNKNOWN_PERIOD")conf-=10;return{metric:metricHint(ctx,String(n?.kind||"NUMBER")),value:n?.value??null,unit:n?.unit??null,role,period:p.code,period_type:p.type,period_year:p.year,freshness:fresh,period_confidence:clamp(conf),context:ctx.slice(0,240)}}
function labelFresh(list:any[]){if(list.some(x=>x.freshness==="CURRENT_OR_RECENT"))return"CÓ SỐ LIỆU GẦN HIỆN TẠI";if(list.some(x=>x.freshness==="FORWARD_LOOKING"))return"CÓ DỮ LIỆU DỰ PHÓNG/KẾ HOẠCH";if(list.some(x=>x.freshness==="UNKNOWN_PERIOD"))return"CẦN KIỂM TRA KỲ SỐ LIỆU";if(list.length)return"DỮ LIỆU LỊCH SỬ";return"KHÔNG CÓ SỐ ĐỊNH LƯỢNG"}

const NI3_RULES=[
 {label:"Ngân hàng",re:/ngan hang|bank|lai suat|tin dung/,inds:["regional banks"],score:78},
 {label:"Chứng khoán",re:/chung khoan|securities|broker|nang hang/,inds:["consumer financial services"],score:76},
 {label:"Bất động sản",re:/bat dong san|real estate|nha o|dat dai/,inds:["real estate operations"],score:78},
 {label:"Dầu khí",re:/dau khi|gia dau|oil|brent|wti|opec/,inds:["oil & gas - integrated","natural gas utilities"],score:82},
 {label:"Thép",re:/thep|steel|quang sat|iron ore/,inds:["iron & steel"],score:82},
 {label:"Điện / Tiện ích",re:/dien|power|electricity|nang luong tai tao/,inds:["electric utilities"],score:78},
 {label:"Xây dựng",re:/xay dung|construction|dau tu cong|ha tang/,inds:["construction services","constr. - supplies & fixtures"],score:74},
 {label:"Thủy sản",re:/thuy san|seafood|tom|ca tra/,inds:["fish\/livestock"],score:80},
 {label:"Dệt may",re:/det may|textile|garment/,inds:["apparel\/accessories"],score:78},
 {label:"Vận tải / Logistics",re:/logistics|cang bien|van tai|shipping/,inds:["water transportation","misc. transportation"],score:76},
 {label:"Công nghệ",re:/cong nghe|technology|phan mem|software/,inds:["computer services","software & programming","communications equipment"],score:74},
 {label:"Bán lẻ",re:/ban le|retail|tieu dung/,inds:["retail (specialty)","retail (catalog & mail order)"],score:72},
 {label:"Bảo hiểm",re:/bao hiem|insurance/,inds:["insurance (miscellaneous)"],score:78}
];
function ni3Links(e:any,r:any,tax:any[],exposures:any[],valid:Set<string>){
 const text=clean([e.event_title,r?.title,r?.summary,e.action_reason,(e.sectors||[]).join(" ")].join(" ")),nt=norm(text),m=new Map<string,any>(),english=/\\b(the|and|for|with|from|shares|stock|earnings|revenue|company|reports|million|billion|takeover|withdraws|files)\\b/i.test(text)&&!/[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/i.test(text);
 const add=(s:any,score:number,reason:string,relation:string)=>{const x=String(s||"").toUpperCase();if(!valid.has(x))return;const old=m.get(x);if(!old||score>old.score)m.set(x,{symbol:x,score,reason,relation})};
 if(!english)for(const x of(e.primary_tickers||[]))add(x,100,"Mã được News Intelligence nhận diện trực tiếp","DIRECT");
 const pats=[/(?:mã|ma)\s*(?:cổ phiếu|co phieu)?\s*[:\-]?\s*([A-Z]{2,5})(?=$|[^A-Z0-9])/g,/(?:HOSE|HNX|UPCOM)\s*:\s*([A-Z]{2,5})(?=$|[^A-Z0-9])/gi,/(?:cổ phiếu|co phieu)\s+([A-Z]{2,5})(?=$|[^A-Z0-9])/g];
 if(!english)for(const re of pats){let z;while((z=re.exec(text))!==null)add(z[1],98,"Mã được nhắc trực tiếp trong nội dung tin","DIRECT_TEXT")}
 if(!english)for(const t of tax){const fn=norm(t.canonical_name);if(fn.length>=7&&nt.includes(fn))add(t.symbol,96,"Tên doanh nghiệp được nhắc trực tiếp","DIRECT_COMPANY")}
 const rules=english?[]:NI3_RULES.filter(q=>q.re.test(nt)||(e.sectors||[]).some((s:string)=>q.re.test(norm(s))));
 for(const q of rules)for(const t of tax){const ind=norm(t.industry_name);if(ind&&q.inds.includes(ind))add(t.symbol,q.score,q.label+" · liên quan theo ngành/lĩnh vực","SECTOR")}
 for(const x of exposures){const terms=(x.match_terms||[]).map((z:any)=>norm(z)).filter((z:string)=>z.length>=3);if(!terms.some((z:string)=>nt.includes(z)))continue;const base=Number(x.confidence||0),verified=x.verification_status==="VERIFIED",score=Math.min(verified?90:84,Math.max(70,base-(verified?0:4)));add(x.symbol,score,x.exposure_label+" · "+(x.relation_type||"RELATED")+" · Knowledge Map","KNOWLEDGE_EXPOSURE")}
 return [...m.values()].sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol)).slice(0,10);
}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method!=="GET")return res(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);try{
 const since=new Date(Date.now()-26*3600000).toISOString();
 const eventCols="id,event_title,event_type,canonical_news_item_id,primary_tickers,sectors,source_ids,lineage_keys,article_count,independent_source_count,fact_summary,number_summary,historical_context,expectation,surprise,verification,market_confirmation,vietnam_transmission,impact_score,confidence_score,action_relevance_score,action_label,action_reason,direction,data_quality_score,evidence_quality_score,last_seen_at,last_scored_at";
 const events:any[]=[];const PAGE=1000;for(let from=0;;from+=PAGE){const{data:page,error}=await db.from("news_intelligence_events").select(eventCols).eq("status","ACTIVE").gte("last_seen_at",since).order("last_seen_at",{ascending:false}).range(from,from+PAGE-1);if(error)throw error;events.push(...(page||[]));if(!page||page.length<PAGE)break;}
 const chunks=<T>(a:T[],n=400)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,(i+1)*n));
 const ids=[...new Set((events||[]).map((e:any)=>e.canonical_news_item_id).filter(Boolean))];let rawMap=new Map<string,any>();if(ids.length){const batches=await Promise.all(chunks(ids).map(async part=>{const{data,error}=await db.from("news_items_raw").select("id,source_id,title,summary,source_url,published_at,fetched_at").in("id",part);if(error)throw error;return data||[]}));const r=batches.flat();rawMap=new Map(r.map((x:any)=>[x.id,x]))}
 const sourceIds=[...new Set((events||[]).flatMap((e:any)=>e.source_ids||[]))];let sourceMap=new Map<string,any>();if(sourceIds.length){const batches=await Promise.all(chunks(sourceIds).map(async part=>{const{data,error}=await db.from("news_sources").select("source_id,source_name,trust_score,category,group_name").in("source_id",part);if(error)throw error;return data||[]}));const s=batches.flat();sourceMap=new Map(s.map((x:any)=>[x.source_id,x]))}
 const [{data:core},{data:market}]=await Promise.all([db.from("stock_core_universe").select("symbol").eq("requested_core",true),db.from("market_eod_universe").select("symbol").eq("eligible",true)]);const universe=[...new Set([...(core||[]).map((x:any)=>x.symbol),...(market||[]).map((x:any)=>x.symbol)])];const valid=new Set<string>(universe);const[{data:tax},{data:exposures}]=await Promise.all([db.from("stock_knowledge_profiles").select("symbol,canonical_name,sector_name,industry_name").eq("entity_type","STOCK").in("symbol",universe),db.from("stock_knowledge_exposures").select("symbol,exposure_type,exposure_key,exposure_label,relation_type,confidence,verification_status,match_terms").in("symbol",universe).in("verification_status",["VERIFIED","INFERRED"])]);
 const out=(events||[]).map((e:any)=>{const r=rawMap.get(e.canonical_news_item_id)||{},links=ni3Links(e,r,tax||[],exposures||[],valid),published=r.published_at||e.last_seen_at||null,nums=(e.number_summary?.observations||[]).slice(-16).map((n:any)=>decorateNumber(n,published));const current=nums.filter((x:any)=>x.freshness==="CURRENT_OR_RECENT"),unknown=nums.filter((x:any)=>x.freshness==="UNKNOWN_PERIOD");const sources=(e.source_ids||[]).slice(0,6).map((id:string)=>{const s=sourceMap.get(id)||{};return{id,name:s.source_name||id,trust_score:s.trust_score??null}});let periodWarning=null;if(unknown.length)periodWarning=`${unknown.length} số liệu chưa xác định chắc kỳ; không nên dùng như số hiện tại.`;else if(nums.length&&!current.length)periodWarning="Chưa có số liệu được xác định là gần hiện tại trong cụm tin này.";return{id:e.id,title:e.event_title,event_type:e.event_type,tickers:e.primary_tickers||[],sectors:e.sectors||[],related_symbols:links,related_strong:links.filter((x:any)=>x.score>=85).map((x:any)=>x.symbol),related_sector:links.filter((x:any)=>x.score>=70&&x.score<85).map((x:any)=>x.symbol),published_at:published,last_seen_at:e.last_seen_at,source_url:r.source_url||null,source_name:(sourceMap.get(r.source_id)||{}).source_name||r.source_id||null,sources,article_count:e.article_count||1,independent_source_count:e.independent_source_count||1,impact_score:e.impact_score,confidence_score:e.confidence_score,action_relevance_score:e.action_relevance_score,action_label:e.action_label,action_reason:e.action_reason||null,direction:e.direction||null,data_quality_score:e.data_quality_score??null,evidence_quality_score:e.evidence_quality_score??null,market_confirmation:e.market_confirmation||null,verification:e.verification||null,vietnam_transmission:e.vietnam_transmission||null,numbers:nums.slice(0,10),freshness_label:labelFresh(nums),period_warning:periodWarning,summary:clean(r.summary||e.fact_summary?.latest?.[0]?.statement||"").slice(0,360)}});
 out.sort((a:any,b:any)=>new Date(b.published_at||b.last_seen_at||0).getTime()-new Date(a.published_at||a.last_seen_at||0).getTime());
 return res(req,{ok:true,engine:"VÕ HOÀNG NEWS INTELLIGENCE V3 PREVIEW",version:"3.3.1-full-24h-pagination",generated_at:new Date().toISOString(),principles:["article_date_is_not_data_period","unknown_period_is_not_current","independent_sources_not_article_count","data_first_narrative_second","no_score_filter_for_24h_list"],universe_size:universe.length,knowledge_profiles:(tax||[]).length,knowledge_exposures:(exposures||[]).length,events:out,total:out.length});
}catch(e){return res(req,{ok:false,error:"PREVIEW_FAILED",detail:String((e as any)?.message||e).slice(0,500)},500)}});
