import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BRIDGE_KEY = Deno.env.get("VH_BRIDGE_KEY") || "";
const V3_URL = `${SUPABASE_URL}/functions/v1/market-live-narrative-v3`;
const ALLOWED = new Set(["https://vohoanginvest.com","https://www.vohoanginvest.com","https://hoangonthi.github.io"]);

type Candidate={family:string;topicKey:string;priority:number;tone:string;headline:string;body:string;watchNext?:string|null;evidence?:any};

function cors(req:Request){const o=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://www.vohoanginvest.com","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"content-type,x-bridge-key","Cache-Control":"no-store","Vary":"Origin"};}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}});}
function sh(extra:Record<string,string>={}){return{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,...extra};}
function n(v:any):number|null{if(v===null||v===undefined||v==="")return null;const x=Number(v);return Number.isFinite(x)?x:null;}
function fmt(v:any,d=2){const x=n(v);return x===null?"—":new Intl.NumberFormat("vi-VN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(x);}
function signed(v:any,d=2){const x=n(v);return x===null?"—":`${x>0?"+":""}${fmt(x,d)}`;}
function pct(v:any,d=2){const x=n(v);return x===null?"—":`${signed(x,d)}%`;}
function vnDate(v:string|Date){const d=v instanceof Date?v:new Date(v);const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const g=(t:string)=>p.find(x=>x.type===t)?.value||"";return`${g("year")}-${g("month")}-${g("day")}`;}
function hash(s:string){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function signBucket(v:number|null){if(v===null)return"unknown";if(v>=.5)return"up";if(v<=-.5)return"down";return"flat";}
function stockMaterial(prev:number|null,curr:number|null){if(prev===null||curr===null)return false;if(Math.abs(curr-prev)>=3)return true;if(signBucket(prev)!==signBucket(curr))return true;if(Math.abs(prev)>=3&&Math.abs(curr)<.5)return true;if(Math.abs(curr)>=3&&Math.abs(prev)<.5)return true;return false;}

async function readJson(path:string,init?:RequestInit){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,init||{headers:sh()});if(!r.ok)return null;return await r.json();}catch{return null;}}
async function restGet(path:string){return await readJson(path,{headers:sh()});}
async function restInsert(table:string,row:any){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:sh({"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify(row)});if(!r.ok)return null;const d=await r.json();return Array.isArray(d)?d[0]||null:d;}catch{return null;}}
async function restPatch(path:string,row:any){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:"PATCH",headers:sh({"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify(row)});if(!r.ok)return null;const d=await r.json();return Array.isArray(d)?d[0]||null:d;}catch{return null;}}
async function restDelete(path:string){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:"DELETE",headers:sh({"Prefer":"return=minimal"})});return r.ok;}catch{return false;}}
async function rpc(name:string,args:any={}){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:sh({"Content-Type":"application/json"}),body:JSON.stringify(args)});if(!r.ok)return null;return await r.json();}catch{return null;}}
async function upsertState(marketDate:string,key:string,value:any){try{await fetch(`${SUPABASE_URL}/rest/v1/market_live_commentary_state?on_conflict=market_date%2Cstate_key`,{method:"POST",headers:sh({"Content-Type":"application/json","Prefer":"resolution=merge-duplicates,return=minimal"}),body:JSON.stringify({market_date:marketDate,state_key:key,value,updated_at:new Date().toISOString()})});}catch{}}
async function getState(marketDate:string,key:string){const rows=await restGet(`market_live_commentary_state?market_date=eq.${marketDate}&state_key=eq.${encodeURIComponent(key)}&select=value,updated_at&limit=1`);return Array.isArray(rows)?rows[0]||null:null;}

function sectorsOf(payload:any){const raw=Array.isArray(payload?.watchlist_sectors)&&payload.watchlist_sectors.length?payload.watchlist_sectors:(Array.isArray(payload?.market?.sectors)?payload.market.sectors:[]);return [...raw].filter((x:any)=>n(x?.change_pct)!==null).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct));}
function stockMap(payload:any){const map=new Map<string,any>();for(const s of sectorsOf(payload)){for(const side of ["top_gainers","top_losers"]){for(const x of (Array.isArray(s?.[side])?s[side]:[])){const sym=String(x?.symbol||"").toUpperCase();if(!sym)continue;const old=map.get(sym),row={...x,symbol:sym,sector:s};if(!old||Math.abs(n(x?.change_pct)??0)>Math.abs(n(old?.change_pct)??0))map.set(sym,row);}}}return map;}
function topLiquidStock(sector:any,side:"top_gainers"|"top_losers"){const rows=Array.isArray(sector?.[side])?sector[side]:[];return rows.find((x:any)=>(n(x?.volume)??0)>=10000)||rows[0]||null;}
function sanitizeSector(sector:any,suppressed:Set<string>){if(!sector||typeof sector!=="object")return sector;return{...sector,top_gainers:(sector.top_gainers||[]).filter((x:any)=>!suppressed.has(String(x?.symbol||"").toUpperCase())),top_losers:(sector.top_losers||[]).filter((x:any)=>!suppressed.has(String(x?.symbol||"").toUpperCase()))};}
function sanitizePayload(payload:any,suppressed:Set<string>){if(!payload||!suppressed.size)return payload;const p=structuredClone(payload);if(Array.isArray(p.watchlist_sectors))p.watchlist_sectors=p.watchlist_sectors.map((s:any)=>sanitizeSector(s,suppressed));if(Array.isArray(p?.market?.sectors))p.market.sectors=p.market.sectors.map((s:any)=>sanitizeSector(s,suppressed));if(p?.world_model?.lines){if(Array.isArray(p.world_model.lines.strongest))p.world_model.lines.strongest=p.world_model.lines.strongest.map((s:any)=>sanitizeSector(s,suppressed));if(Array.isArray(p.world_model.lines.weakest))p.world_model.lines.weakest=p.world_model.lines.weakest.map((s:any)=>sanitizeSector(s,suppressed));}if(p?.world_model?.driver){if(p.world_model.driver.sector)p.world_model.driver.sector=sanitizeSector(p.world_model.driver.sector,suppressed);if(Array.isArray(p.world_model.driver.players))p.world_model.driver.players=p.world_model.driver.players.filter((x:any)=>!suppressed.has(String(x?.symbol||"").toUpperCase()));}return p;}

function latestStockEvents(events:any[]){const m=new Map<string,any>();for(const e of events){if(!String(e?.event_type||"").startsWith("STOCK_"))continue;const sym=String(e?.facts?.stock?.symbol||"").toUpperCase();if(sym&&!m.has(sym))m.set(sym,e);}return m;}
function previousStockEvent(events:any[],symbol:string,currentId:number){return events.find(e=>Number(e?.id)!==currentId&&String(e?.event_type||"").startsWith("STOCK_")&&String(e?.facts?.stock?.symbol||"").toUpperCase()===symbol)||null;}
function stockRewrite(event:any,prev:any){const s=event?.facts?.stock||{},sector=event?.facts?.sector||{},world=event?.facts?.world||{},sym=String(s?.symbol||"").toUpperCase(),curr=n(s?.change_pct),old=n(prev?.facts?.stock?.change_pct),delta=curr!==null&&old!==null?curr-old:null;let headline=String(event?.title||`${sym} có biến động đáng chú ý`),tone=curr!==null&&curr<0?"warning":"neutral";if(prev&&curr!==null&&old!==null){const a=signBucket(old),b=signBucket(curr);if(a!==b){headline=`${sym} vừa đảo trạng thái so với lần nhắc trước`;tone=b==="down"?"warning":b==="up"?"positive":"neutral";}else if(delta!==null&&delta>=3){headline=`${sym} tăng tốc thêm so với lần nhắc trước`;tone="positive";}else if(delta!==null&&delta<=-3){headline=`${sym} hạ nhiệt rõ so với lần nhắc trước`;tone=curr<0?"warning":"neutral";}}
  const v=world?.ball||{},b=world?.match?.breadth||{},parts:string[]=[];if(prev&&old!==null&&curr!==null)parts.push(`Lần trước ${sym} ở ${pct(old)}, hiện là ${pct(curr)}; biên độ đã thay đổi ${signed(delta,2)} điểm phần trăm.`);else if(curr!==null)parts.push(`${sym} hiện thay đổi ${pct(curr)}${sector?.name?` trong nhóm ${sector.name}`:""}.`);if(sector?.name&&n(sector?.change_pct)!==null)parts.push(`Toàn nhóm ${sector.name} đang ở ${pct(sector.change_pct)}${n(sector?.adv)!==null&&n(sector?.dec)!==null?`, với ${Math.round(sector.adv)} mã tăng/${Math.round(sector.dec)} mã giảm`:""}.`);if(n(v?.value)!==null)parts.push(`VN-Index lúc này ở ${fmt(v.value,2)} điểm${n(v?.change)!==null?`, ${signed(v.change,2)} điểm`:""}.`);if(n(b?.adv)!==null&&n(b?.dec)!==null)parts.push(`Độ rộng: ${Math.round(b.adv)} mã tăng và ${Math.round(b.dec)} mã giảm.`);return{headline,tone,body:parts.join(" "),watch_next:`Theo dõi xem biến động của ${sym} có lan sang các mã cùng nhóm hay chỉ là chuyển động riêng lẻ.`};}

function recentMentions(comments:any[],symbol:string,minutes=35){const now=Date.now(),re=new RegExp(`(^|[^A-Z])${symbol}([^A-Z]|$)`,`i`);return comments.some(c=>now-new Date(c?.published_at||0).getTime()<=minutes*60000&&re.test(`${c?.headline||""} ${c?.body||""}`));}
function recentTopic(comments:any[],topicKey:string,minutes:number){const now=Date.now();return comments.some(c=>now-new Date(c?.published_at||0).getTime()<=minutes*60000&&String(c?.evidence?.router?.topic_key||"")===topicKey);}
function previousMarketFromComments(comments:any[]){for(const c of comments){const w=c?.evidence?.world_model||{},m=c?.evidence?.market_snapshot||{};const value=n(w?.ball?.value)??n(m?.value),adv=n(w?.match?.breadth?.adv)??n(m?.adv),dec=n(w?.match?.breadth?.dec)??n(m?.dec);if(value!==null||adv!==null||dec!==null)return{value,adv,dec};}return{};}
function previousDerivativeFromComments(comments:any[]){for(const c of comments){const d=c?.evidence?.outside_context?.derivatives||c?.evidence?.derivatives;if(n(d?.last_price)!==null||d?.trend)return{last_price:n(d?.last_price),trend:String(d?.trend||"").toUpperCase()};}return{};}

async function buildLoopCandidate(marketDate:string,capturedAt:string,payload:any,recentComments:any[]):Promise<Candidate|null>{
  const sectors=sectorsOf(payload),v=payload?.market?.vnindex||{},strong=sectors[0]||null,weak=sectors.at(-1)||null;
  const [der,hot,marketState,derState,topics,ecos]=await Promise.all([rpc("derivatives_public_v1"),rpc("hot_stocks_public_v1"),getState(marketDate,"market"),getState(marketDate,"derivatives"),restGet("market_live_background_topics?is_active=eq.true&select=id,topic_key,title,body,source_label,freshness,min_interval_minutes,metadata&order=id.asc"),restGet("market_live_ecosystems?is_active=eq.true&select=ecosystem_key,ecosystem_name,symbol,relation_label,sort_order&order=ecosystem_key.asc,sort_order.asc")]);
  const candidates:Candidate[]=[],seed=hash(`${marketDate}|${Math.floor(new Date(capturedAt).getTime()/300000)}`),phase=seed%11;
  const prevM=marketState?.value||previousMarketFromComments(recentComments),adv=n(v?.adv),dec=n(v?.dec),prevAdv=n(prevM?.adv),prevDec=n(prevM?.dec),idx=n(v?.value),prevIdx=n(prevM?.value),idxDelta=idx!==null&&prevIdx!==null?idx-prevIdx:null;

  if(strong&&weak&&idx!==null){const rawStock=topLiquidStock(strong,"top_gainers"),stock=rawStock?.symbol&&!recentMentions(recentComments,String(rawStock.symbol).toUpperCase(),22)?rawStock:null;const openers=[`VN-Index đang ở ${fmt(idx,2)} điểm; nhìn xuống bên trong, ${strong.name} đang đứng đầu nhóm ngành.`,`Điểm số là một phần câu chuyện: VN-Index ${fmt(idx,2)}, còn ${strong.name} đang là nhóm nổi bật nhất lúc này.`,`Thế trận hiện không chỉ nằm ở VN-Index ${fmt(idx,2)} điểm; dòng vận động đang nổi rõ hơn ở ${strong.name}.`];let body=openers[seed%openers.length];if(n(strong.change_pct)!==null)body+=` ${strong.name} bình quân ${pct(strong.change_pct)}`;if(stock?.symbol&&n(stock?.change_pct)!==null)body+=`, trong nhóm ${stock.symbol} đang nổi hơn với ${pct(stock.change_pct)}`;body+=".";if(weak&&!String(weak.name).includes(strong.name))body+=` Ở chiều ngược lại, ${weak.name} đang yếu nhất nhóm theo dõi với ${pct(weak.change_pct)}.`;candidates.push({family:"market_chain",topicKey:`market-chain-${strong.key||strong.name}`,priority:idxDelta!==null&&Math.abs(idxDelta)>=1?3:2,tone:"neutral",headline:idxDelta!==null&&Math.abs(idxDelta)>=1?`VN-Index vừa ${idxDelta>0?"nhích lên":"lùi xuống"}, nhóm dẫn cũng đang đổi nhịp`:`Từ VN-Index xuống nhóm ngành: câu chuyện lúc này đang nằm ở ${strong.name}`,body,watchNext:`Nhìn tiếp xem ${strong.name} có giữ được độ lan tỏa và ${weak?.name||"nhóm yếu"} có thu hẹp khoảng cách hay không.`,evidence:{market_snapshot:{value:idx,adv,dec}}});}

  if(adv!==null&&dec!==null&&prevAdv!==null&&prevDec!==null){const da=adv-prevAdv,dd=dec-prevDec;if(Math.abs(da)>=6||Math.abs(dd)>=6){const better=da-dd>0;candidates.push({family:"breadth",topicKey:`breadth-${Math.sign(da-dd)}`,priority:3,tone:better?"positive":"warning",headline:better?"Độ rộng vừa mở thêm về phía tăng":"Độ rộng đang hẹp lại so với nhịp trước",body:`Hiện có ${Math.round(adv)} mã tăng/${Math.round(dec)} mã giảm. So với lần quét trước, số mã tăng ${da>=0?"tăng":"giảm"} ${Math.abs(Math.round(da))} mã, số mã giảm ${dd>=0?"tăng":"giảm"} ${Math.abs(Math.round(dd))} mã. Đây là thay đổi của mặt bằng cổ phiếu, đáng nhìn cùng với điểm số VN-Index.`,watchNext:"Nếu độ rộng tiếp tục thay đổi cùng chiều với chỉ số, chất lượng nhịp đi sẽ rõ hơn; nếu lệch pha, cần thận trọng với phần điểm số bề mặt.",evidence:{market_snapshot:{value:idx,adv,dec}}});}}

  if(sectors.length>=2){const top2=sectors.slice(0,2),bottom=sectors.at(-1),rawStock=topLiquidStock(top2[0],"top_gainers"),s1=rawStock?.symbol&&!recentMentions(recentComments,String(rawStock.symbol).toUpperCase(),22)?rawStock:null;let body=`Bản đồ nhóm ngành đang cho thấy ${top2.map((s:any)=>`${s.name} ${pct(s.change_pct)}`).join(" · ")}.`;if(bottom)body+=` Ở đầu còn lại, ${bottom.name} ${pct(bottom.change_pct)}.`;if(s1?.symbol&&(n(s1.volume)??0)>=10000)body+=` Trong nhóm dẫn, ${s1.symbol} là mã đáng chú ý hơn với ${pct(s1.change_pct)}.`;candidates.push({family:"sector_scan",topicKey:`sector-scan-${top2.map((x:any)=>x.key||x.name).join("-")}`,priority:2,tone:"neutral",headline:`Bản đồ ngành: ${top2[0].name} đang dẫn, ${bottom?.name||"nhóm yếu"} ở phía sau`,body,watchNext:"Theo dõi xem vị trí dẫn đầu có đổi nhóm hay sức mạnh bắt đầu lan rộng sang nhóm thứ hai, thứ ba.",evidence:{market_snapshot:{value:idx,adv,dec}}});}

  const prevDer=derState?.value||previousDerivativeFromComments(recentComments),derTrend=String(der?.trend||"").toUpperCase(),derPrice=n(der?.last_price),prevDerPrice=n(prevDer?.last_price),prevDerTrend=String(prevDer?.trend||"").toUpperCase(),derDelta=derPrice!==null&&prevDerPrice!==null?derPrice-prevDerPrice:null;
  if(derTrend&&(prevDerTrend&&derTrend!==prevDerTrend||derDelta!==null&&Math.abs(derDelta)>=1)){let body=`Phái sinh hiện ${derTrend.includes("GIAM")?"nghiêng giảm":derTrend.includes("TANG")?"nghiêng tăng":"đang đổi trạng thái"}`;if(derPrice!==null)body+=` quanh ${fmt(derPrice,1)}`;if(derDelta!==null)body+=`, ${derDelta>0?"cao hơn":"thấp hơn"} ${fmt(Math.abs(derDelta),1)} điểm so với mốc so sánh gần nhất`;body+=". Đây là lớp tham chiếu cho thế trận, không dùng một mình để giải thích cơ sở.";candidates.push({family:"derivatives",topicKey:`derivatives-${derTrend}-${derDelta===null?0:Math.sign(derDelta)}`,priority:3,tone:derTrend.includes("GIAM")?"warning":"neutral",headline:prevDerTrend&&derTrend!==prevDerTrend?"Phái sinh vừa đổi trạng thái":"Phái sinh vừa có nhịp thay đổi đáng chú ý",body,watchNext:"Nhìn tiếp mức độ đồng thuận hay lệch pha giữa phái sinh, VN-Index và độ rộng cổ phiếu.",evidence:{derivatives:{trend:derTrend,last_price:derPrice}}});}

  const hotObj=hot&&typeof hot==="object"?hot:{},hotStocks=Array.isArray(hotObj?.stocks)?hotObj.stocks:[];
  if(hotObj?.fresh===true&&hotStocks.length){const available=hotStocks.filter((x:any)=>x?.symbol&&!recentMentions(recentComments,String(x.symbol).toUpperCase(),28));const hs=available[(seed>>3)%Math.max(1,available.length)]||null;if(hs){const sym=String(hs.symbol).toUpperCase();let body=`Trong danh sách “Cổ phiếu đáng chú ý hôm nay”, ${sym} đang có tín hiệu dòng tiền ${String(hs.signal_class||"").toLowerCase()||"đáng chú ý"}, T-score ${Math.round(n(hs.t_score)??0)}/100 và thay đổi ${pct(hs.change_pct)}.`;if(n(hs.value_traded_bn)!==null)body+=` Giá trị giao dịch ghi nhận khoảng ${fmt(hs.value_traded_bn,1)} tỷ đồng.`;body+=" Đây là tín hiệu theo dõi ngắn hạn, không phải khuyến nghị mua.";candidates.push({family:"hot_stocks",topicKey:`hot-${sym}`,priority:2,tone:"neutral",headline:`Quay lại danh sách dòng tiền: ${sym} đang đáng chú ý`,body,watchNext:`Theo dõi xem tín hiệu dòng tiền của ${sym} có được duy trì cùng thanh khoản và mặt bằng nhóm ngành hay không.`,evidence:{hot_stock:hs,market_snapshot:{value:idx,adv,dec}}});}
    const liquid=hotStocks.filter((x:any)=>n(x?.value_traded_bn)!==null).sort((a:any,b:any)=>Number(b.value_traded_bn)-Number(a.value_traded_bn));if(liquid.length>=3){const top=liquid.slice(0,3);candidates.push({family:"flow_scan",topicKey:`flow-${top.map((x:any)=>x.symbol).join("-")}`,priority:2,tone:"neutral",headline:`Dòng tiền ngắn hạn đang tập trung ở một số mã nổi bật`,body:`Danh sách tín hiệu dòng tiền hiện có ${hotStocks.length} mã. Theo giá trị giao dịch, nhóm nổi bật hơn gồm ${top.map((x:any)=>`${x.symbol} khoảng ${fmt(x.value_traded_bn,1)} tỷ`).join(" · ")}. Số lượng mã có tín hiệu và chất lượng thanh khoản quan trọng hơn việc nhìn một cổ phiếu đơn lẻ.`,watchNext:"Theo dõi xem danh sách có mở rộng thêm và giá trị giao dịch có tiếp tục tăng hay chỉ tập trung ở vài mã.",evidence:{hot_count:hotStocks.length,top_value:top,market_snapshot:{value:idx,adv,dec}}});}}

  const ecoRows=Array.isArray(ecos)?ecos:[];if(ecoRows.length){const sm=stockMap(payload),groups=new Map<string,any[]>();for(const r of ecoRows){if(!groups.has(r.ecosystem_key))groups.set(r.ecosystem_key,[]);groups.get(r.ecosystem_key)!.push(r);}for(const [key,rows] of groups){const seen=rows.map(r=>({meta:r,stock:sm.get(String(r.symbol).toUpperCase())})).filter(x=>x.stock&&n(x.stock.change_pct)!==null);if(seen.length>=2){const mover=[...seen].sort((a,b)=>Math.abs(n(b.stock.change_pct)??0)-Math.abs(n(a.stock.change_pct)??0))[0],peers=seen.filter(x=>x!==mover).slice(0,3);if(Math.abs(n(mover.stock.change_pct)??0)>=2&&!recentTopic(recentComments,`ecosystem-${key}`,35)){candidates.push({family:"ecosystem",topicKey:`ecosystem-${key}`,priority:2,tone:"neutral",headline:`${mover.stock.symbol} đang chuyển động, nhìn rộng ra hệ sinh thái ${rows[0].ecosystem_name}`,body:`${mover.stock.symbol} hiện ${pct(mover.stock.change_pct)}. Các mã cùng hệ sinh thái đang có dữ liệu: ${peers.map(x=>`${x.stock.symbol} ${pct(x.stock.change_pct)}`).join(" · ")}. Cách nhìn này giúp phân biệt một mã chạy riêng với chuyển động có tính đồng thuận.`,watchNext:"Nếu nhiều mã trong cùng hệ sinh thái cùng mở rộng biên độ, câu chuyện sẽ đáng chú ý hơn một chuyển động đơn lẻ.",evidence:{market_snapshot:{value:idx,adv,dec}}});break;}}}}

  const topicRows=Array.isArray(topics)?topics:[];for(const t of topicRows){const wait=Math.max(45,Number(t.min_interval_minutes)||75);if(!recentTopic(recentComments,`background-${t.topic_key}`,wait)){candidates.push({family:"background",topicKey:`background-${t.topic_key}`,priority:2,tone:"neutral",headline:t.title,body:`Ngoài nhịp giá trong phiên, có một câu chuyện nền đáng nhớ: ${t.body}`,watchNext:"Xem đây là bối cảnh dài hơn của thị trường; các mốc roadmap không được dùng như xác nhận cho trạng thái hiện tại nếu chưa có dữ liệu mới.",evidence:{background:{source_label:t.source_label,freshness:t.freshness,current_fact:false,metadata:t.metadata},market_snapshot:{value:idx,adv,dec}}});break;}}

  await Promise.all([upsertState(marketDate,"market",{value:idx,adv,dec,captured_at:capturedAt}),derTrend?upsertState(marketDate,"derivatives",{trend:derTrend,last_price:derPrice,captured_at:capturedAt}):Promise.resolve()]);
  if(!candidates.length)return null;const allowed=candidates.filter(c=>!recentTopic(recentComments,c.topicKey,c.family==="background"?75:c.family==="hot_stocks"?28:18));if(!allowed.length)return null;const urgent=allowed.filter(c=>c.priority>=3),pool=urgent.length?urgent:allowed;pool.sort((a,b)=>(hash(`${seed}|${a.topicKey}`)%1000)-(hash(`${seed}|${b.topicKey}`)%1000));return pool[phase%pool.length]||pool[0];
}

async function publishLoop(marketDate:string,capturedAt:string,c:Candidate,snapshotId:number){return await restInsert("market_live_comments",{market_date:marketDate,published_at:capturedAt,event_id:null,snapshot_id:snapshotId,tone:c.tone,headline:c.headline,body:c.body,watch_next:c.watchNext||null,evidence:{...(c.evidence||{}),router:{version:"v4.1",family:c.family,topic_key:c.topicKey,selection:"seeded-rotation"}},source_mode:"commentary-loop-v1",is_final:false});}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);const key=req.headers.get("x-bridge-key")||"";if(!BRIDGE_KEY||key!==BRIDGE_KEY)return json(req,{ok:false,error:"UNAUTHORIZED"},401);let input:any;try{input=await req.json();}catch{return json(req,{ok:false,error:"INVALID_JSON"},400);}if(!input?.ok)return json(req,{ok:false,error:"INVALID_PAYLOAD"},400);const capturedAt=typeof input?.captured_at==="string"&&!Number.isNaN(new Date(input.captured_at).getTime())?new Date(input.captured_at).toISOString():new Date().toISOString(),marketDate=vnDate(capturedAt);
  let upstream:any=null;try{const r=await fetch(V3_URL,{method:"POST",headers:{"Content-Type":"application/json; charset=utf-8","x-bridge-key":key},body:JSON.stringify(input)}),text=await r.text();try{upstream=JSON.parse(text);}catch{upstream={ok:false,error:"V3_BAD_JSON",detail:text.slice(0,300)}}if(!r.ok)return json(req,{...upstream,router:{version:"v4.1",stage:"v3",status:r.status}},r.status);}catch(e){return json(req,{ok:false,error:"V3_UNAVAILABLE",detail:String((e as Error)?.message||e).slice(0,240)},502);}
  const [currentRows,recentEvents,recentComments,snapRows]=await Promise.all([restGet(`market_live_current?id=eq.vietnam&market_date=eq.${marketDate}&select=id,captured_at,payload&limit=1`),restGet(`market_live_events?market_date=eq.${marketDate}&select=id,detected_at,event_type,event_key,severity,title,facts&order=id.desc&limit=100`),restGet(`market_live_comments?market_date=eq.${marketDate}&select=id,published_at,headline,body,evidence,source_mode,event_id&order=published_at.desc,id.desc&limit=50`),restGet(`market_live_snapshots?market_date=eq.${marketDate}&select=id,captured_at&order=captured_at.desc,id.desc&limit=1`)]);let current=Array.isArray(currentRows)?currentRows[0]||null:null;const events=Array.isArray(recentEvents)?recentEvents:[],comments=Array.isArray(recentComments)?recentComments:[],snapshotId=Number(Array.isArray(snapRows)?snapRows[0]?.id:0)||0;let published=upstream?.published_comment||null,event=upstream?.event||null,suppressed:any=null,rewritten:any=null,keepSymbol="";
  if(event?.id&&String(event?.type||"").startsWith("STOCK_")){const ev=events.find((x:any)=>Number(x.id)===Number(event.id))||null,sym=String(ev?.facts?.stock?.symbol||"").toUpperCase(),curr=n(ev?.facts?.stock?.change_pct),prev=previousStockEvent(events,sym,Number(event.id)),old=n(prev?.facts?.stock?.change_pct);keepSymbol=sym;if(prev&&!stockMaterial(old,curr)){const commentRows=await restGet(`market_live_comments?event_id=eq.${Number(event.id)}&select=id&order=id.desc&limit=1`),cid=Number(Array.isArray(commentRows)?commentRows[0]?.id:0)||0;if(cid)await restDelete(`market_live_comments?id=eq.${cid}`);await restDelete(`market_live_events?id=eq.${Number(event.id)}`);suppressed={type:event.type,symbol:sym,reason:"NO_MATERIAL_CHANGE",previous_pct:old,current_pct:curr,threshold_pp:3};published=null;event=null;keepSymbol="";}else if(ev){const rw=stockRewrite(ev,prev),commentRows=await restGet(`market_live_comments?event_id=eq.${Number(event.id)}&select=id,evidence&order=id.desc&limit=1`),cr=Array.isArray(commentRows)?commentRows[0]||null:null;if(cr?.id){rewritten=await restPatch(`market_live_comments?id=eq.${Number(cr.id)}`,{tone:rw.tone,headline:rw.headline,body:rw.body,watch_next:rw.watch_next,evidence:{...(cr.evidence||{}),router:{version:"v4.1",stock_symbol:sym,previous_pct:old,current_pct:curr,material_change_pp:old!==null&&curr!==null?Math.round((curr-old)*1000)/1000:null}}});published=rewritten||published;}if(prev){let et="STOCK_MOVE";if(signBucket(old)!==signBucket(curr))et="STOCK_REVERSAL";else if(curr!==null&&old!==null&&curr-old>=3)et="STOCK_ACCELERATE";else if(curr!==null&&old!==null&&curr-old<=-3)et="STOCK_RETRACE";await restPatch(`market_live_events?id=eq.${Number(event.id)}`,{event_type:et,title:rw.headline});event={...event,type:et,title:rw.headline};}}}
  if(current?.payload){const sm=stockMap(current.payload),lastBySymbol=latestStockEvents(events),suppressedSymbols=new Set<string>();for(const [sym,last] of lastBySymbol){if(sym===keepSymbol)continue;const cur=sm.get(sym),cp=n(cur?.change_pct),lp=n(last?.facts?.stock?.change_pct);if(cur&&cp!==null&&lp!==null&&!stockMaterial(lp,cp))suppressedSymbols.add(sym);}if(suppressedSymbols.size){const clean=sanitizePayload(current.payload,suppressedSymbols);await restPatch(`market_live_current?id=eq.vietnam&market_date=eq.${marketDate}`,{payload:clean,updated_at:new Date().toISOString()});current={...current,payload:clean};}}
  let loopComment:any=null;if(!published&&current?.payload&&snapshotId){const latest=comments[0]||null,age=latest?new Date(capturedAt).getTime()-new Date(latest.published_at).getTime():Infinity;if(age>=4.5*60000){const c=await buildLoopCandidate(marketDate,capturedAt,current.payload,comments);if(c)loopComment=await publishLoop(marketDate,capturedAt,c,snapshotId);}}else if(current?.payload){const v=current.payload?.market?.vnindex||{},der=await rpc("derivatives_public_v1");await Promise.all([upsertState(marketDate,"market",{value:n(v?.value),adv:n(v?.adv),dec:n(v?.dec),captured_at:capturedAt}),der?.trend?upsertState(marketDate,"derivatives",{trend:String(der.trend).toUpperCase(),last_price:n(der.last_price),captured_at:capturedAt}):Promise.resolve()]);}
  return json(req,{...upstream,engine:"market-live-commentary-router-v4.1",published_comment:loopComment||published||null,event,router:{version:"v4.1",suppressed,rewritten:Boolean(rewritten),loop_family:loopComment?.evidence?.router?.family||null,novelty_rule:"stock repeat only after >=3 percentage-point change or state reversal",selection:"V3 urgent events first; rotating market/sector/flow/hot-stock/ecosystem/background topics fill quiet periods"}});
});
