import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BRIDGE_KEY=Deno.env.get("VH_BRIDGE_KEY")||"";
const V5_URL=`${SUPABASE_URL}/functions/v1/market-live-narrative-v5`;
const MIN_STOCK_VOLUME=200000;
const ALLOWED=new Set(["https://vohoanginvest.com","https://www.vohoanginvest.com","https://hoangonthi.github.io"]);

type Story={family:string;topicKey:string;tone:string;headline:string;body:string;watchNext:string;evidence?:any};

function cors(req:Request){const o=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://www.vohoanginvest.com","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"content-type,x-bridge-key","Cache-Control":"no-store","Vary":"Origin"};}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}});}
function sh(extra:Record<string,string>={}){return{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,...extra};}
function n(v:any):number|null{if(v===null||v===undefined||v==="")return null;const x=Number(v);return Number.isFinite(x)?x:null;}
function fmt(v:any,d=2){const x=n(v);return x===null?"—":new Intl.NumberFormat("vi-VN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(x);}
function signed(v:any,d=2){const x=n(v);return x===null?"—":`${x>0?"+":""}${fmt(x,d)}`;}
function pct(v:any,d=2){const x=n(v);return x===null?"—":`${signed(x,d)}%`;}
function vnDate(v:string|Date){const d=v instanceof Date?v:new Date(v);const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d);const g=(t:string)=>p.find(x=>x.type===t)?.value||"";return`${g("year")}-${g("month")}-${g("day")}`;}
function vnMinute(v:string|Date){const d=v instanceof Date?v:new Date(v);const p=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Ho_Chi_Minh",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(d);const g=(t:string)=>Number(p.find(x=>x.type===t)?.value||0);return g("hour")*60+g("minute");}
function hash(s:string){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}

async function restGet(path:string){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:sh()});if(!r.ok)return null;return await r.json();}catch{return null;}}
async function restInsert(table:string,row:any){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}`,{method:"POST",headers:sh({"Content-Type":"application/json","Prefer":"return=representation"}),body:JSON.stringify(row)});if(!r.ok)return null;const d=await r.json();return Array.isArray(d)?d[0]||null:d;}catch{return null;}}

function sectorsOf(p:any){const raw=Array.isArray(p?.watchlist_sectors)&&p.watchlist_sectors.length?p.watchlist_sectors:(Array.isArray(p?.market?.sectors)?p.market.sectors:[]);return [...raw].filter((s:any)=>n(s?.change_pct)!==null).sort((a:any,b:any)=>Number(b.change_pct)-Number(a.change_pct));}
function liquidStocks(p:any){const map=new Map<string,any>();for(const s of sectorsOf(p)){for(const side of ["top_gainers","top_losers"]){for(const x of (Array.isArray(s?.[side])?s[side]:[])){const sym=String(x?.symbol||"").toUpperCase(),vol=n(x?.volume),cp=n(x?.change_pct);if(!sym||vol===null||vol<MIN_STOCK_VOLUME||cp===null)continue;const row={...x,symbol:sym,sector:s};const old=map.get(sym);if(!old||Math.abs(cp)>Math.abs(n(old.change_pct)??0))map.set(sym,row);}}}return [...map.values()];}
function recentTopic(comments:any[],key:string,minutes:number,capturedAt:string){const now=new Date(capturedAt).getTime();return comments.some(c=>{const t=new Date(c?.published_at||0).getTime(),k=String(c?.evidence?.router?.topic_key||"");return k===key&&now-t>=0&&now-t<minutes*60000;});}
function lastSystemAge(comments:any[],capturedAt:string){const now=new Date(capturedAt).getTime();const row=comments.find(c=>{const s=String(c?.source_mode||"");return s.startsWith("narrative-")||s.startsWith("commentary-");});if(!row)return Infinity;return now-new Date(row.published_at).getTime();}

function indexStory(p:any,topicKey="v6-index"):Story|null{const v=p?.market?.vnindex||{},w=p?.world_model||{},b=w?.ball||{},value=n(v?.value)??n(b?.value);if(value===null)return null;const d5=n(b?.delta_5m),d15=n(b?.delta_15m),high=n(v?.high),low=n(v?.low);let body=`VN-Index hiện ở ${fmt(value,2)} điểm, ${signed(v?.change,2)} điểm (${pct(v?.change_pct)}).`;if(d5!==null||d15!==null)body+=` Nhịp gần: 5 phút ${signed(d5,2)} điểm${d15!==null?`, 15 phút ${signed(d15,2)} điểm`:""}.`;if(high!==null&&low!==null)body+=` Biên phiên hiện ${fmt(low,2)}–${fmt(high,2)}.`;return{family:"index_pulse",topicKey,tone:"neutral",headline:"VN-Index: nhìn riêng nhịp của chỉ số",body,watchNext:"Chỉ cập nhật lại câu chuyện VN-Index khi nhịp ngắn hoặc vị trí so với đỉnh/đáy phiên thay đổi đáng kể."};}
function breadthStory(p:any,topicKey="v6-breadth"):Story|null{const v=p?.market?.vnindex||{},adv=n(v?.adv),dec=n(v?.dec),flat=n(v?.flat);if(adv===null||dec===null)return null;const body=`Độ rộng hiện có ${Math.round(adv)} mã tăng và ${Math.round(dec)} mã giảm${flat!==null?`, ${Math.round(flat)} mã đứng giá`:""}.`;return{family:"breadth_pulse",topicKey,tone:adv>=dec?"positive":"warning",headline:adv>=dec?"Độ rộng đang nghiêng về phía tăng":"Độ rộng đang nghiêng về phía giảm",body,watchNext:"Nhìn tiếp xem chênh lệch tăng/giảm có tiếp tục mở rộng hay thu hẹp ở lần quét kế tiếp."};}
function sectorStory(p:any,topicKey="v6-sector"):Story|null{const s=sectorsOf(p);if(!s.length)return null;const top=s[0],next=s[1],weak=s.at(-1);let body=`${top.name} đang dẫn nhóm ngành với ${pct(top.change_pct)}`;if(next)body+=`, kế đến ${next.name} ${pct(next.change_pct)}`;body+=".";if(weak&&weak!==top)body+=` Ở phía cuối bảng, ${weak.name} ${pct(weak.change_pct)}.`;const liq=(top.top_gainers||[]).filter((x:any)=>(n(x?.volume)??0)>=MIN_STOCK_VOLUME).slice(0,3);if(liq.length)body+=` Mã thanh khoản đủ lớn nổi bật trong nhóm: ${liq.map((x:any)=>`${x.symbol} ${pct(x.change_pct)}`).join(", ")}.`;return{family:"sector_map",topicKey,tone:"neutral",headline:`Bản đồ ngành: ${top.name} đang đứng đầu`,body,watchNext:`Theo dõi xem vị trí của ${top.name} có được giữ đến nhịp sau hay xuất hiện luân chuyển sang nhóm khác.`};}
function liquidMoverStory(p:any,topicKey="v6-liquid-movers"):Story|null{const rows=liquidStocks(p).sort((a,b)=>Math.abs(n(b.change_pct)??0)-Math.abs(n(a.change_pct)??0));if(!rows.length)return null;const top=rows.slice(0,4);return{family:"liquid_movers",topicKey,tone:"neutral",headline:"Các cổ phiếu thanh khoản đủ lớn đang biến động nổi bật",body:`Trong nhóm mã đã giao dịch từ 200.000 cp trở lên, ${top.map((x:any)=>`${x.symbol} ${pct(x.change_pct)} (${x.sector?.name||""})`).join(" · ")}.`,watchNext:"Chỉ tiếp tục nhắc một mã nếu biên độ thay đổi đủ lớn, đảo trạng thái hoặc xuất hiện sự kiện giá mới đáng chú ý."};}
function technicalStory(p:any,topicKey="v6-technical"):Story|null{const v=p?.market?.vnindex||{},t=p?.technical||{},w=p?.world_model||{},value=n(v?.value);if(value===null)return null;const bits:string[]=[];for(const [label,key] of [["VWAP","vwap"],["MA20","ma20"],["MA10","ma10"]] as const){const x=n(t?.[key]);if(x!==null)bits.push(`${value>=x?"trên":"dưới"} ${label} ${fmt(x,1)}`);}const above=w?.zones?.nearest_above,below=w?.zones?.nearest_below;if(above&&n(above.value)!==null)bits.push(`cản gần ${above.label} ${fmt(above.value,1)}`);if(below&&n(below.value)!==null)bits.push(`đỡ gần ${below.label} ${fmt(below.value,1)}`);if(!bits.length)return null;return{family:"technical_position",topicKey,tone:"neutral",headline:"Vị trí kỹ thuật của VN-Index",body:`VN-Index ${fmt(value,2)} điểm đang ${bits.slice(0,4).join("; ")}.`,watchNext:"Theo dõi phản ứng của chỉ số tại vùng kỹ thuật gần nhất, không cần kéo thêm câu chuyện ngành nếu chưa có thay đổi riêng."};}

function phaseStory(p:any,capturedAt:string):Story|null{const m=vnMinute(capturedAt),v=p?.market?.vnindex||{},w=p?.world_model||{},b=w?.ball||{},value=n(v?.value)??n(b?.value),high=n(v?.high),low=n(v?.low),adv=n(v?.adv),dec=n(v?.dec),valueB=n(v?.value_b),sectors=sectorsOf(p),liquid=liquidStocks(p).sort((a,b)=>Math.abs(n(b.change_pct)??0)-Math.abs(n(a.change_pct)??0));if(value===null)return null;
  if(m>=840&&m<870){const remain=870-m;const bucket=m<855?"30":m<860?"15":m<865?"10":"5";let body=`Còn khoảng ${remain} phút trước khi bước vào ATC. VN-Index đang ở ${fmt(value,2)} điểm, ${signed(v?.change,2)} điểm (${pct(v?.change_pct)}).`;if(high!==null)body+=` Chỉ số đang cách đỉnh phiên khoảng ${fmt(Math.max(0,high-value),2)} điểm.`;return{family:"pre_atc",topicKey:`pre-atc-${bucket}`,tone:"neutral",headline:`Còn khoảng ${remain} phút trước ATC`,body,watchNext:"Nhìn xem VN-Index tiến vào ATC ở gần đỉnh hay lùi khỏi đỉnh; đây là câu chuyện chính của phần cuối phiên."};}
  if(m>=870&&m<885){const remain=885-m,slot=Math.floor((m-870)/5);let body=`ATC đang diễn ra, còn khoảng ${remain} phút đến 14:45. VN-Index hiện ${fmt(value,2)} điểm, ${signed(v?.change,2)} điểm (${pct(v?.change_pct)}).`;if(high!==null&&low!==null)body+=` Vị trí hiện tại cách đỉnh phiên ${fmt(Math.max(0,high-value),2)} điểm và cao hơn đáy ${fmt(Math.max(0,value-low),2)} điểm.`;return{family:"atc",topicKey:`atc-${slot}`,tone:"neutral",headline:slot===0?"ATC bắt đầu":"ATC đang đi vào những phút cuối",body,watchNext:"Theo dõi vị trí đóng cửa so với đỉnh phiên và vùng kỹ thuật gần nhất; hạn chế suy diễn từ một vài mã riêng lẻ trong ATC."};}
  if(m>=885&&m<=901){const slot=Math.min(4,Math.floor((m-885)/3));if(slot===0){let body=`VN-Index ở trạng thái cuối phiên quanh ${fmt(value,2)} điểm, ${signed(v?.change,2)} điểm (${pct(v?.change_pct)}).`;if(high!==null&&low!==null)body+=` Biên phiên ${fmt(low,2)}–${fmt(high,2)}; điểm cuối cách đỉnh khoảng ${fmt(Math.max(0,high-value),2)} điểm.`;return{family:"close_index",topicKey:"close-index",tone:n(v?.change)>=0?"positive":"warning",headline:"Trạng thái cuối phiên của VN-Index",body,watchNext:"Đây là mốc chốt của chỉ số; các câu chuyện tiếp theo chuyển sang độ rộng, nhóm ngành và vị trí kỹ thuật cuối phiên."};}
    if(slot===1&&adv!==null&&dec!==null){return{family:"close_breadth",topicKey:"close-breadth",tone:adv>=dec?"positive":"warning",headline:"Độ rộng cuối phiên",body:`Cuối phiên ghi nhận ${Math.round(adv)} mã tăng/${Math.round(dec)} mã giảm${valueB!==null?`, giá trị giao dịch khoảng ${fmt(valueB,1)} tỷ đồng`:""}.`,watchNext:"Dùng độ rộng cuối phiên để đối chiếu với mức tăng/giảm của chỉ số: điểm số mạnh nhưng độ rộng hẹp là một câu chuyện khác với tăng có lan tỏa."};}
    if(slot===2&&sectors.length){const top=sectors.slice(0,3),weak=sectors.at(-1);return{family:"close_sector",topicKey:"close-sector",tone:"neutral",headline:"Bản đồ ngành cuối phiên",body:`Nhóm nổi bật cuối phiên: ${top.map((x:any)=>`${x.name} ${pct(x.change_pct)}`).join(" · ")}${weak?`. Phía yếu nhất: ${weak.name} ${pct(weak.change_pct)}.`:""}`,watchNext:"Đây là bản đồ để mang sang phần rà soát sau phiên: nhóm nào giữ sức mạnh, nhóm nào chỉ bật ngắn trong ngày."};}
    if(slot===3&&liquid.length){return{family:"close_stocks",topicKey:"close-stocks",tone:"neutral",headline:"Cổ phiếu thanh khoản lớn nổi bật cuối phiên",body:`Trong các mã đã giao dịch từ 200.000 cp trở lên, nổi bật gồm ${liquid.slice(0,5).map((x:any)=>`${x.symbol} ${pct(x.change_pct)}`).join(" · ")}.`,watchNext:"Các mã này mới đủ điều kiện để đưa vào câu chuyện cổ phiếu cuối phiên; mã thanh khoản thấp tiếp tục bị loại khỏi bình luận tự động."};}
    const tech=technicalStory(p,"close-technical");if(tech)return{...tech,family:"close_technical",headline:"Vị trí kỹ thuật cuối phiên",watchNext:"Dùng vị trí đóng cửa so với VWAP, MA và vùng cản/đỡ làm mốc tham chiếu cho phiên kế tiếp."};
  }
  return null;
}

function generalStory(p:any,capturedAt:string,comments:any[]):Story|null{const bucket=Math.floor(new Date(capturedAt).getTime()/300000),builders=[indexStory,breadthStory,sectorStory,liquidMoverStory,technicalStory];for(let i=0;i<builders.length;i++){const idx=(hash(`${bucket}|${i}`)+i)%builders.length,c=builders[idx](p,`v6-${["index","breadth","sector","stocks","technical"][idx]}`);if(c&&!recentTopic(comments,c.topicKey,14,capturedAt))return c;}return null;}
async function publish(marketDate:string,capturedAt:string,snapshotId:number,c:Story){return await restInsert("market_live_comments",{market_date:marketDate,published_at:capturedAt,event_id:null,snapshot_id:snapshotId||null,tone:c.tone,headline:c.headline,body:c.body,watch_next:c.watchNext,evidence:{...(c.evidence||{}),router:{version:"v6.0",family:c.family,topic_key:c.topicKey,selection:"second-chance-or-session-phase",min_stock_volume:MIN_STOCK_VOLUME}},source_mode:"commentary-phase-v6",is_final:false});}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="POST")return json(req,{ok:false,error:"METHOD_NOT_ALLOWED"},405);const key=req.headers.get("x-bridge-key")||"";if(!BRIDGE_KEY||key!==BRIDGE_KEY)return json(req,{ok:false,error:"UNAUTHORIZED"},401);let input:any;try{input=await req.json();}catch{return json(req,{ok:false,error:"INVALID_JSON"},400);}if(!input?.ok)return json(req,{ok:false,error:"INVALID_PAYLOAD"},400);
  const capturedAt=typeof input?.captured_at==="string"&&!Number.isNaN(new Date(input.captured_at).getTime())?new Date(input.captured_at).toISOString():new Date().toISOString(),marketDate=vnDate(capturedAt);
  let upstream:any;try{const r=await fetch(V5_URL,{method:"POST",headers:{"Content-Type":"application/json; charset=utf-8","x-bridge-key":key},body:JSON.stringify(input)}),text=await r.text();try{upstream=JSON.parse(text);}catch{upstream={ok:false,error:"V5_BAD_JSON",detail:text.slice(0,300)}}if(!r.ok)return json(req,{...upstream,session_router:{version:"v6.0",stage:"v5",status:r.status}},r.status);}catch(e){return json(req,{ok:false,error:"V5_UNAVAILABLE",detail:String((e as Error)?.message||e).slice(0,240)},502);}
  const [curRows,comments,snaps]=await Promise.all([restGet(`market_live_current?id=eq.vietnam&market_date=eq.${marketDate}&select=payload&limit=1`),restGet(`market_live_comments?market_date=eq.${marketDate}&select=id,published_at,source_mode,evidence,headline&order=published_at.desc,id.desc&limit=60`),restGet(`market_live_snapshots?market_date=eq.${marketDate}&select=id&order=captured_at.desc,id.desc&limit=1`)]);const payload=Array.isArray(curRows)?curRows[0]?.payload||null:null,recent=Array.isArray(comments)?comments:[],snapshotId=Number(Array.isArray(snaps)?snaps[0]?.id:0)||0;
  let published=upstream?.published_comment||null,extra:any=null;const m=vnMinute(capturedAt),endgame=m>=840&&m<=901,age=lastSystemAge(recent,capturedAt),minAge=endgame?150000:270000;
  if(!published&&payload&&age>=minAge){let c=endgame?phaseStory(payload,capturedAt):null;if(c&&recentTopic(recent,c.topicKey,c.family.startsWith("close_")?1440:8,capturedAt))c=null;if(!c)c=generalStory(payload,capturedAt,recent);if(c){published=await publish(marketDate,capturedAt,snapshotId,c);extra={family:c.family,topic_key:c.topicKey,reason:endgame?"SESSION_PHASE":"SECOND_CHANCE_AFTER_QUIET_OR_SUPPRESSION"};}}
  return json(req,{...upstream,engine:"market-live-commentary-session-v6",published_comment:published,session_router:{version:"v6.0",min_stock_volume:MIN_STOCK_VOLUME,second_chance:true,endgame_window:"14:00-15:01",pre_atc:"14:00-14:30",atc:"14:30-14:45",close_state:"14:45-15:01",extra_story:extra,rule:"Nếu một ứng viên bị lọc (ví dụ volume <200k), vòng kể chuyện phải chọn câu chuyện khác thay vì im lặng. Cuối phiên có thuật toán riêng theo trạng thái thời gian."}});
});
