import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!;
const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const B=`${U}/functions/v1`;
const H={apikey:K,Authorization:`Bearer ${K}`};
async function j(url:string,ms:number){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{Accept:"application/json"},signal:c.signal});const x=await r.json().catch(()=>null);if(!r.ok||!x?.ok)throw new Error(`${url.split('/').at(-1)}:${r.status}`);return x}finally{clearTimeout(t)}}
async function cur(){const r=await fetch(`${U}/rest/v1/morning_intelligence_snapshot?id=eq.current&select=version,payload&limit=1`,{headers:H});if(!r.ok)return null;return (await r.json())?.[0]||null}
async function save(p:any,v:number){const now=new Date().toISOString();const row={id:"current",version:v,payload:p,generated_at:now,source_decision_at:p.decision?.generated_at||now,source_macro_at:p.macro?.generated_at||p.macro?.as_of||null,source_hot_at:p.hot?.updated_at||p.hot?.generated_at||null,last_error:null,updated_at:now};const r=await fetch(`${U}/rest/v1/morning_intelligence_snapshot?on_conflict=id`,{method:"POST",headers:{...H,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(row)});if(!r.ok)throw new Error(`save:${r.status}`)}
Deno.serve(async(req:Request)=>{if(!["GET","POST"].includes(req.method))return new Response("method",{status:405});try{const old=await cur(),base=old?.payload||{};const [d,m,h]=await Promise.allSettled([j(`${B}/morning-decision-test`,25000),j(`${B}/macro-anchor-public`,6000),j(`${B}/hot-stocks-feed`,6000)]);const decision=d.status==="fulfilled"?d.value:base.decision;if(!decision?.ok)throw new Error("decision unavailable");const payload={decision,macro:m.status==="fulfilled"?m.value:(base.macro||{ok:false,cards:[]}),hot:h.status==="fulfilled"?h.value:(base.hot||{ok:false,stocks:[]})};const version=Number(old?.version||0)+1;await save(payload,version);return new Response(JSON.stringify({ok:true,version,sources:{decision:d.status,macro:m.status,hot:h.status}}),{headers:{"Content-Type":"application/json"}})}catch(e){return new Response(JSON.stringify({ok:false,error:"SNAPSHOT_BUILD_FAILED",detail:String((e as Error)?.message||e)}),{status:500,headers:{"Content-Type":"application/json"}})}});
