create table if not exists public.market_live_user_comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  display_name text not null default 'Nhà đầu tư',
  body text not null,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  constraint market_live_user_comments_body_len check (char_length(btrim(body)) between 1 and 800),
  constraint market_live_user_comments_name_len check (char_length(display_name) between 1 and 60)
);

create index if not exists market_live_user_comments_created_at_idx on public.market_live_user_comments (created_at desc);
create index if not exists market_live_user_comments_user_created_idx on public.market_live_user_comments (user_id, created_at desc);

alter table public.market_live_user_comments enable row level security;

drop policy if exists market_live_user_comments_read on public.market_live_user_comments;
create policy market_live_user_comments_read
on public.market_live_user_comments
for select
to anon, authenticated
using (is_visible = true and created_at >= now() - interval '7 days');

drop policy if exists market_live_user_comments_insert on public.market_live_user_comments;
create policy market_live_user_comments_insert
on public.market_live_user_comments
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists market_live_user_comments_delete_own on public.market_live_user_comments;
create policy market_live_user_comments_delete_own
on public.market_live_user_comments
for delete
to authenticated
using (user_id = auth.uid());

grant select on public.market_live_user_comments to anon, authenticated;
grant insert, delete on public.market_live_user_comments to authenticated;
grant usage, select on sequence public.market_live_user_comments_id_seq to authenticated;

create or replace function public.market_live_prepare_user_comment()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_name text;
  v_last timestamptz;
begin
  if v_uid is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select max(created_at) into v_last
  from public.market_live_user_comments
  where user_id = v_uid;

  if v_last is not null and v_last > now() - interval '12 seconds' then
    raise exception 'COMMENT_RATE_LIMIT';
  end if;

  select coalesce(
    nullif(btrim(raw_user_meta_data->>'display_name'), ''),
    nullif(btrim(raw_user_meta_data->>'full_name'), ''),
    nullif(btrim(raw_user_meta_data->>'name'), ''),
    'Nhà đầu tư'
  ) into v_name
  from auth.users
  where id = v_uid;

  new.user_id := v_uid;
  new.display_name := left(coalesce(v_name, 'Nhà đầu tư'), 60);
  new.body := btrim(new.body);
  new.created_at := now();
  new.is_visible := true;
  return new;
end;
$$;

revoke all on function public.market_live_prepare_user_comment() from public;

drop trigger if exists trg_market_live_prepare_user_comment on public.market_live_user_comments;
create trigger trg_market_live_prepare_user_comment
before insert on public.market_live_user_comments
for each row execute function public.market_live_prepare_user_comment();

create or replace function public.cleanup_market_live_7d()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.market_live_user_comments where created_at < now() - interval '7 days';
  delete from public.market_live_admin_notes where created_at < now() - interval '7 days';
  delete from public.market_live_comments where created_at < now() - interval '7 days';
end;
$$;

revoke all on function public.cleanup_market_live_7d() from public, anon, authenticated;
grant execute on function public.cleanup_market_live_7d() to service_role;

do $$
declare
  v_jobid bigint;
begin
  for v_jobid in select jobid from cron.job where jobname = 'market_live_retention_7d_hourly'
  loop
    perform cron.unschedule(v_jobid);
  end loop;
  perform cron.schedule(
    'market_live_retention_7d_hourly',
    '17 * * * *',
    'select public.cleanup_market_live_7d();'
  );
end $$;
